<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 16 Applications: Infer categorical | Montana State Introductory Statistics with R</title>
  <meta name="description" content="Open resources textbook for Stat 216 at Montana State University" />
  <meta name="generator" content="bookdown 0.47 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 16 Applications: Infer categorical | Montana State Introductory Statistics with R" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Open resources textbook for Stat 216 at Montana State University" />
  <meta name="github-repo" content="MTstateIntroStats/IntroStatTextbook" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 16 Applications: Infer categorical | Montana State Introductory Statistics with R" />
  
  <meta name="twitter:description" content="Open resources textbook for Stat 216 at Montana State University" />
  

<meta name="author" content="Stacey Hancock, Nicole Carnegie, Elijah Meyer, Jade Schmidt, Melinda Yager, Mark Greenwood" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="inference-two-props.html"/>
<link rel="next" href="inference-one-mean.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="libs/bsTable-3.3.7/bootstrapTable.min.css" rel="stylesheet" />
<script src="libs/bsTable-3.3.7/bootstrapTable.js"></script>
<script src="libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.12.1/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.2.2/css/crosstalk.min.css" rel="stylesheet" />
<script src="libs/crosstalk-1.2.2/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-2.25.2/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-2.25.2/plotly-latest.min.js"></script>
<link href="libs/htmltools-fill-0.5.9/fill.css" rel="stylesheet" />


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="css/ims-style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">MSU Intro Stat with R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome</a></li>
<li class="chapter" data-level="" data-path="authors.html"><a href="authors.html"><i class="fa fa-check"></i>Authors</a></li>
<li class="chapter" data-level="" data-path="preface.html"><a href="preface.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="" data-path="preface.html"><a href="preface.html#textbook-overview"><i class="fa fa-check"></i>Textbook overview</a>
<ul>
<li class="chapter" data-level="" data-path="preface.html"><a href="preface.html#examples-and-exercises"><i class="fa fa-check"></i>Examples and exercises</a></li>
<li class="chapter" data-level="" data-path="preface.html"><a href="preface.html#data-sets-and-their-sources"><i class="fa fa-check"></i>Data sets and their sources</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="preface.html"><a href="preface.html#stat-216-coursepack"><i class="fa fa-check"></i>STAT 216 Coursepack</a></li>
<li class="chapter" data-level="" data-path="preface.html"><a href="preface.html#acknowledgements"><i class="fa fa-check"></i>Acknowledgements</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="rstudio.html"><a href="rstudio.html"><i class="fa fa-check"></i>Preliminaries: Getting started in RStudio</a>
<ul>
<li class="chapter" data-level="" data-path="rstudio.html"><a href="rstudio.html#accessing-rstudio"><i class="fa fa-check"></i>Accessing RStudio</a>
<ul>
<li class="chapter" data-level="" data-path="rstudio.html"><a href="rstudio.html#alternative-options-for-accessing-rstudio"><i class="fa fa-check"></i>Alternative options for accessing RStudio</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="rstudio.html"><a href="rstudio.html#packages"><i class="fa fa-check"></i>Packages</a>
<ul>
<li class="chapter" data-level="" data-path="rstudio.html"><a href="rstudio.html#using-packages"><i class="fa fa-check"></i>Using packages</a></li>
<li class="chapter" data-level="" data-path="rstudio.html"><a href="rstudio.html#the-catstats-package"><i class="fa fa-check"></i>The <code>catstats</code> package</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="rstudio.html"><a href="rstudio.html#projects"><i class="fa fa-check"></i>Projects</a></li>
<li class="chapter" data-level="" data-path="rstudio.html"><a href="rstudio.html#r-script-files"><i class="fa fa-check"></i>R script files</a>
<ul>
<li class="chapter" data-level="" data-path="rstudio.html"><a href="rstudio.html#try-it"><i class="fa fa-check"></i>Try it!</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="rstudio.html"><a href="rstudio.html#loading-data"><i class="fa fa-check"></i>Loading data</a>
<ul>
<li class="chapter" data-level="" data-path="rstudio.html"><a href="rstudio.html#try-it-1"><i class="fa fa-check"></i>Try it!</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="rstudio.html"><a href="rstudio.html#exporting-files"><i class="fa fa-check"></i>Exporting files</a>
<ul>
<li class="chapter" data-level="" data-path="rstudio.html"><a href="rstudio.html#exporting-r-script-files"><i class="fa fa-check"></i>Exporting R script files</a></li>
<li class="chapter" data-level="" data-path="rstudio.html"><a href="rstudio.html#try-it-2"><i class="fa fa-check"></i>Try it!</a></li>
<li class="chapter" data-level="" data-path="rstudio.html"><a href="rstudio.html#exporting-plots"><i class="fa fa-check"></i>Exporting plots</a></li>
<li class="chapter" data-level="" data-path="rstudio.html"><a href="rstudio.html#try-it-3"><i class="fa fa-check"></i>Try it!</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="rstudio.html"><a href="rstudio.html#home"><i class="fa fa-check"></i>Home</a></li>
<li class="chapter" data-level="" data-path="rstudio.html"><a href="rstudio.html#troubleshooting"><i class="fa fa-check"></i>Troubleshooting</a></li>
<li class="chapter" data-level="" data-path="rstudio.html"><a href="rstudio.html#extra-references"><i class="fa fa-check"></i>Extra references</a></li>
</ul></li>
<li class="part"><span><b>I Introduction to data</b></span></li>
<li class="chapter" data-level="1" data-path="data-hello.html"><a href="data-hello.html"><i class="fa fa-check"></i><b>1</b> Hello data</a>
<ul>
<li class="chapter" data-level="1.1" data-path="data-hello.html"><a href="data-hello.html#basic-stents-strokes"><i class="fa fa-check"></i><b>1.1</b> Case study: using stents to prevent strokes</a></li>
<li class="chapter" data-level="1.2" data-path="data-hello.html"><a href="data-hello.html#data-basics"><i class="fa fa-check"></i><b>1.2</b> Data basics</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="data-hello.html"><a href="data-hello.html#observations-variables-and-data-frames"><i class="fa fa-check"></i><b>1.2.1</b> Observations, variables, and data frames</a></li>
<li class="chapter" data-level="1.2.2" data-path="data-hello.html"><a href="data-hello.html#variable-types"><i class="fa fa-check"></i><b>1.2.2</b> Types of variables</a></li>
<li class="chapter" data-level="1.2.3" data-path="data-hello.html"><a href="data-hello.html#variable-relations"><i class="fa fa-check"></i><b>1.2.3</b> Relationships between variables</a></li>
<li class="chapter" data-level="1.2.4" data-path="data-hello.html"><a href="data-hello.html#explanatory-and-response-variables"><i class="fa fa-check"></i><b>1.2.4</b> Explanatory and response variables</a></li>
<li class="chapter" data-level="1.2.5" data-path="data-hello.html"><a href="data-hello.html#introducing-observational-studies-and-experiments"><i class="fa fa-check"></i><b>1.2.5</b> Introducing observational studies and experiments</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="data-hello.html"><a href="data-hello.html#chp1-review"><i class="fa fa-check"></i><b>1.3</b> Chapter review</a>
<ul>
<li class="chapter" data-level="" data-path="data-hello.html"><a href="data-hello.html#summary"><i class="fa fa-check"></i>Summary</a></li>
<li class="chapter" data-level="" data-path="data-hello.html"><a href="data-hello.html#terms"><i class="fa fa-check"></i>Terms</a></li>
<li class="chapter" data-level="" data-path="data-hello.html"><a href="data-hello.html#key-ideas"><i class="fa fa-check"></i>Key ideas</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="data-design.html"><a href="data-design.html"><i class="fa fa-check"></i><b>2</b> Study design</a>
<ul>
<li class="chapter" data-level="2.1" data-path="data-design.html"><a href="data-design.html#sampling-principles-strategies"><i class="fa fa-check"></i><b>2.1</b> Sampling principles and strategies</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="data-design.html"><a href="data-design.html#populations-and-samples"><i class="fa fa-check"></i><b>2.1.1</b> Populations and samples</a></li>
<li class="chapter" data-level="2.1.2" data-path="data-design.html"><a href="data-design.html#parameters-and-statistics"><i class="fa fa-check"></i><b>2.1.2</b> Parameters and statistics</a></li>
<li class="chapter" data-level="2.1.3" data-path="data-design.html"><a href="data-design.html#anecdotal-evidence"><i class="fa fa-check"></i><b>2.1.3</b> Anecdotal evidence</a></li>
<li class="chapter" data-level="2.1.4" data-path="data-design.html"><a href="data-design.html#sampling-from-a-population"><i class="fa fa-check"></i><b>2.1.4</b> Sampling from a population</a></li>
<li class="chapter" data-level="2.1.5" data-path="data-design.html"><a href="data-design.html#samp-methods"><i class="fa fa-check"></i><b>2.1.5</b> Four sampling methods (special topic)</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="data-design.html"><a href="data-design.html#observational-studies"><i class="fa fa-check"></i><b>2.2</b> Observational studies</a></li>
<li class="chapter" data-level="2.3" data-path="data-design.html"><a href="data-design.html#experiments"><i class="fa fa-check"></i><b>2.3</b> Experiments</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="data-design.html"><a href="data-design.html#principles-of-experimental-design"><i class="fa fa-check"></i><b>2.3.1</b> Principles of experimental design</a></li>
<li class="chapter" data-level="2.3.2" data-path="data-design.html"><a href="data-design.html#reducing-bias-human-experiments"><i class="fa fa-check"></i><b>2.3.2</b> Reducing bias in human experiments</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="data-design.html"><a href="data-design.html#scope-of-inference"><i class="fa fa-check"></i><b>2.4</b> Scope of inference</a></li>
<li class="chapter" data-level="2.5" data-path="data-design.html"><a href="data-design.html#chp2-review"><i class="fa fa-check"></i><b>2.5</b> Chapter review</a>
<ul>
<li class="chapter" data-level="" data-path="data-design.html"><a href="data-design.html#summary-1"><i class="fa fa-check"></i>Summary</a></li>
<li class="chapter" data-level="" data-path="data-design.html"><a href="data-design.html#terms-1"><i class="fa fa-check"></i>Terms</a></li>
<li class="chapter" data-level="" data-path="data-design.html"><a href="data-design.html#key-ideas-1"><i class="fa fa-check"></i>Key ideas</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="data-applications.html"><a href="data-applications.html"><i class="fa fa-check"></i><b>3</b> Applications: Data</a>
<ul>
<li class="chapter" data-level="3.1" data-path="data-applications.html"><a href="data-applications.html#dataframes-in-r"><i class="fa fa-check"></i><b>3.1</b> Dataframes in R</a></li>
<li class="chapter" data-level="3.2" data-path="data-applications.html"><a href="data-applications.html#datastruc"><i class="fa fa-check"></i><b>3.2</b> Tidy structure of data</a></li>
<li class="chapter" data-level="3.3" data-path="data-applications.html"><a href="data-applications.html#using-the-pipe-to-chain"><i class="fa fa-check"></i><b>3.3</b> Using the pipe to chain</a></li>
<li class="chapter" data-level="3.4" data-path="data-applications.html"><a href="data-applications.html#a-data-wrangling-example"><i class="fa fa-check"></i><b>3.4</b> A data wrangling example</a>
<ul>
<li class="chapter" data-level="" data-path="data-applications.html"><a href="data-applications.html#filtering"><i class="fa fa-check"></i>Filtering</a></li>
<li class="chapter" data-level="" data-path="data-applications.html"><a href="data-applications.html#mutating"><i class="fa fa-check"></i>Mutating</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="data-applications.html"><a href="data-applications.html#terms-2"><i class="fa fa-check"></i>Terms</a></li>
<li class="chapter" data-level="" data-path="data-applications.html"><a href="data-applications.html#r-functions"><i class="fa fa-check"></i>R functions</a></li>
</ul></li>
<li class="part"><span><b>II Exploratory data analysis</b></span></li>
<li class="chapter" data-level="4" data-path="explore-categorical.html"><a href="explore-categorical.html"><i class="fa fa-check"></i><b>4</b> Exploring categorical data</a>
<ul>
<li class="chapter" data-level="4.1" data-path="explore-categorical.html"><a href="explore-categorical.html#contingency-tables-and-conditional-proportions"><i class="fa fa-check"></i><b>4.1</b> Contingency tables and conditional proportions</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="explore-categorical.html"><a href="explore-categorical.html#row-and-column-proportions"><i class="fa fa-check"></i><b>4.1.1</b> Row and column proportions</a></li>
<li class="chapter" data-level="4.1.2" data-path="explore-categorical.html"><a href="explore-categorical.html#sample-proportions-and-population-proportions"><i class="fa fa-check"></i><b>4.1.2</b> Sample proportions and population proportions</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="explore-categorical.html"><a href="explore-categorical.html#bar-plots-and-mosaic-plots"><i class="fa fa-check"></i><b>4.2</b> Bar plots and mosaic plots</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="explore-categorical.html"><a href="explore-categorical.html#mosaic-plots"><i class="fa fa-check"></i><b>4.2.1</b> Mosaic plots</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="explore-categorical.html"><a href="explore-categorical.html#why-not-pie-charts"><i class="fa fa-check"></i><b>4.3</b> Why not pie charts?</a></li>
<li class="chapter" data-level="4.4" data-path="explore-categorical.html"><a href="explore-categorical.html#simpson"><i class="fa fa-check"></i><b>4.4</b> Simpson’s paradox</a></li>
<li class="chapter" data-level="4.5" data-path="explore-categorical.html"><a href="explore-categorical.html#chp4-review"><i class="fa fa-check"></i><b>4.5</b> Chapter review</a>
<ul>
<li class="chapter" data-level="" data-path="explore-categorical.html"><a href="explore-categorical.html#summary-2"><i class="fa fa-check"></i>Summary</a></li>
<li class="chapter" data-level="" data-path="explore-categorical.html"><a href="explore-categorical.html#terms-3"><i class="fa fa-check"></i>Terms</a></li>
<li class="chapter" data-level="" data-path="explore-categorical.html"><a href="explore-categorical.html#key-ideas-2"><i class="fa fa-check"></i>Key ideas</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="explore-numerical.html"><a href="explore-numerical.html"><i class="fa fa-check"></i><b>5</b> Exploring quantitative data</a>
<ul>
<li class="chapter" data-level="5.1" data-path="explore-numerical.html"><a href="explore-numerical.html#scatterplots"><i class="fa fa-check"></i><b>5.1</b> Scatterplots for paired data</a></li>
<li class="chapter" data-level="5.2" data-path="explore-numerical.html"><a href="explore-numerical.html#dotplots"><i class="fa fa-check"></i><b>5.2</b> Dot plots and the mean</a></li>
<li class="chapter" data-level="5.3" data-path="explore-numerical.html"><a href="explore-numerical.html#histograms"><i class="fa fa-check"></i><b>5.3</b> Histograms and shape</a></li>
<li class="chapter" data-level="5.4" data-path="explore-numerical.html"><a href="explore-numerical.html#variance-sd"><i class="fa fa-check"></i><b>5.4</b> Variance and standard deviation</a></li>
<li class="chapter" data-level="5.5" data-path="explore-numerical.html"><a href="explore-numerical.html#box-plots-quartiles-and-the-median"><i class="fa fa-check"></i><b>5.5</b> Box plots, quartiles, and the median</a></li>
<li class="chapter" data-level="5.6" data-path="explore-numerical.html"><a href="explore-numerical.html#describing-and-comparing-quantitative-distributions"><i class="fa fa-check"></i><b>5.6</b> Describing and comparing quantitative distributions</a></li>
<li class="chapter" data-level="5.7" data-path="explore-numerical.html"><a href="explore-numerical.html#robust-statistics"><i class="fa fa-check"></i><b>5.7</b> Robust statistics</a></li>
<li class="chapter" data-level="5.8" data-path="explore-numerical.html"><a href="explore-numerical.html#transforming-data-special-topic"><i class="fa fa-check"></i><b>5.8</b> Transforming data (special topic)</a></li>
<li class="chapter" data-level="5.9" data-path="explore-numerical.html"><a href="explore-numerical.html#mapping-data-special-topic"><i class="fa fa-check"></i><b>5.9</b> Mapping data (special topic)</a></li>
<li class="chapter" data-level="5.10" data-path="explore-numerical.html"><a href="explore-numerical.html#chp5-review"><i class="fa fa-check"></i><b>5.10</b> Chapter review</a>
<ul>
<li class="chapter" data-level="" data-path="explore-numerical.html"><a href="explore-numerical.html#summary-3"><i class="fa fa-check"></i>Summary</a></li>
<li class="chapter" data-level="" data-path="explore-numerical.html"><a href="explore-numerical.html#terms-4"><i class="fa fa-check"></i>Terms</a></li>
<li class="chapter" data-level="" data-path="explore-numerical.html"><a href="explore-numerical.html#key-ideas-3"><i class="fa fa-check"></i>Key ideas</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="explore-regression.html"><a href="explore-regression.html"><i class="fa fa-check"></i><b>6</b> Correlation and regression</a>
<ul>
<li class="chapter" data-level="6.1" data-path="explore-regression.html"><a href="explore-regression.html#fit-line-res-cor"><i class="fa fa-check"></i><b>6.1</b> Fitting a line, residuals, and correlation</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="explore-regression.html"><a href="explore-regression.html#fitting-a-line-to-data"><i class="fa fa-check"></i><b>6.1.1</b> Fitting a line to data</a></li>
<li class="chapter" data-level="6.1.2" data-path="explore-regression.html"><a href="explore-regression.html#using-linear-regression-to-predict-possum-head-lengths"><i class="fa fa-check"></i><b>6.1.2</b> Using linear regression to predict possum head lengths</a></li>
<li class="chapter" data-level="6.1.3" data-path="explore-regression.html"><a href="explore-regression.html#residuals"><i class="fa fa-check"></i><b>6.1.3</b> Residuals</a></li>
<li class="chapter" data-level="6.1.4" data-path="explore-regression.html"><a href="explore-regression.html#describing-linear-relationships-with-correlation"><i class="fa fa-check"></i><b>6.1.4</b> Describing linear relationships with correlation</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="explore-regression.html"><a href="explore-regression.html#least-squares-regression"><i class="fa fa-check"></i><b>6.2</b> Least squares regression</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="explore-regression.html"><a href="explore-regression.html#gift-aid-for-freshman-at-elmhurst-college"><i class="fa fa-check"></i><b>6.2.1</b> Gift aid for freshman at Elmhurst College</a></li>
<li class="chapter" data-level="6.2.2" data-path="explore-regression.html"><a href="explore-regression.html#an-objective-measure-for-finding-the-best-line"><i class="fa fa-check"></i><b>6.2.2</b> An objective measure for finding the best line</a></li>
<li class="chapter" data-level="6.2.3" data-path="explore-regression.html"><a href="explore-regression.html#finding-and-interpreting-the-least-squares-line"><i class="fa fa-check"></i><b>6.2.3</b> Finding and interpreting the least squares line</a></li>
<li class="chapter" data-level="6.2.4" data-path="explore-regression.html"><a href="explore-regression.html#calculating-the-least-squares-regression-line-using-summary-statistics-special-topic"><i class="fa fa-check"></i><b>6.2.4</b> Calculating the least squares regression line using summary statistics (special topic)</a></li>
<li class="chapter" data-level="6.2.5" data-path="explore-regression.html"><a href="explore-regression.html#extrapolation-is-treacherous"><i class="fa fa-check"></i><b>6.2.5</b> Extrapolation is treacherous</a></li>
<li class="chapter" data-level="6.2.6" data-path="explore-regression.html"><a href="explore-regression.html#describing-the-strength-of-a-fit"><i class="fa fa-check"></i><b>6.2.6</b> Describing the strength of a fit</a></li>
<li class="chapter" data-level="6.2.7" data-path="explore-regression.html"><a href="explore-regression.html#categorical-predictor-two-levels"><i class="fa fa-check"></i><b>6.2.7</b> Categorical predictors with two levels (special topic)</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="explore-regression.html"><a href="explore-regression.html#outliers-in-regression"><i class="fa fa-check"></i><b>6.3</b> Outliers in linear regression</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="explore-regression.html"><a href="explore-regression.html#types-of-outliers"><i class="fa fa-check"></i><b>6.3.1</b> Types of outliers</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="explore-regression.html"><a href="explore-regression.html#chp6-review"><i class="fa fa-check"></i><b>6.4</b> Chapter review</a>
<ul>
<li class="chapter" data-level="" data-path="explore-regression.html"><a href="explore-regression.html#summary-4"><i class="fa fa-check"></i>Summary</a></li>
<li class="chapter" data-level="" data-path="explore-regression.html"><a href="explore-regression.html#data-visualization-summary"><i class="fa fa-check"></i>Data visualization summary</a></li>
<li class="chapter" data-level="" data-path="explore-regression.html"><a href="explore-regression.html#summary-measures"><i class="fa fa-check"></i>Summary measures</a></li>
<li class="chapter" data-level="" data-path="explore-regression.html"><a href="explore-regression.html#notation-summary"><i class="fa fa-check"></i>Notation summary</a></li>
<li class="chapter" data-level="" data-path="explore-regression.html"><a href="explore-regression.html#terms-5"><i class="fa fa-check"></i>Terms</a></li>
<li class="chapter" data-level="" data-path="explore-regression.html"><a href="explore-regression.html#key-ideas-4"><i class="fa fa-check"></i>Key ideas</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="explore-mult-reg.html"><a href="explore-mult-reg.html"><i class="fa fa-check"></i><b>7</b> Multivariable models</a>
<ul>
<li class="chapter" data-level="7.1" data-path="explore-mult-reg.html"><a href="explore-mult-reg.html#gapminder-world"><i class="fa fa-check"></i><b>7.1</b> Gapminder world</a></li>
<li class="chapter" data-level="7.2" data-path="explore-mult-reg.html"><a href="explore-mult-reg.html#simpsons-paradox-revisited"><i class="fa fa-check"></i><b>7.2</b> Simpson’s paradox revisited</a></li>
<li class="chapter" data-level="7.3" data-path="explore-mult-reg.html"><a href="explore-mult-reg.html#regression-multiple-predictors"><i class="fa fa-check"></i><b>7.3</b> Multiple regression (special topic)</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="explore-mult-reg.html"><a href="explore-mult-reg.html#ind-and-cat-predictors"><i class="fa fa-check"></i><b>7.3.1</b> Indicator and categorical predictors</a></li>
<li class="chapter" data-level="7.3.2" data-path="explore-mult-reg.html"><a href="explore-mult-reg.html#many-predictors-in-a-model"><i class="fa fa-check"></i><b>7.3.2</b> Many predictors in a model</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="explore-mult-reg.html"><a href="explore-mult-reg.html#chp7-review"><i class="fa fa-check"></i><b>7.4</b> Chapter review</a>
<ul>
<li class="chapter" data-level="" data-path="explore-mult-reg.html"><a href="explore-mult-reg.html#summary-5"><i class="fa fa-check"></i>Summary</a></li>
<li class="chapter" data-level="" data-path="explore-mult-reg.html"><a href="explore-mult-reg.html#terms-6"><i class="fa fa-check"></i>Terms</a></li>
<li class="chapter" data-level="" data-path="explore-mult-reg.html"><a href="explore-mult-reg.html#key-ideas-5"><i class="fa fa-check"></i>Key ideas</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="explore-applications.html"><a href="explore-applications.html"><i class="fa fa-check"></i><b>8</b> Applications: Explore</a></li>
<li class="part"><span><b>III Foundations of inference</b></span></li>
<li class="chapter" data-level="9" data-path="foundations-randomization.html"><a href="foundations-randomization.html"><i class="fa fa-check"></i><b>9</b> Hypothesis testing with randomization</a>
<ul>
<li class="chapter" data-level="9.1" data-path="foundations-randomization.html"><a href="foundations-randomization.html#Martian"><i class="fa fa-check"></i><b>9.1</b> Motivating example: Martian alphabet</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="foundations-randomization.html"><a href="foundations-randomization.html#observed-data"><i class="fa fa-check"></i><b>9.1.1</b> Observed data</a></li>
<li class="chapter" data-level="9.1.2" data-path="foundations-randomization.html"><a href="foundations-randomization.html#variability-in-a-statistic"><i class="fa fa-check"></i><b>9.1.2</b> Variability in a statistic</a></li>
<li class="chapter" data-level="9.1.3" data-path="foundations-randomization.html"><a href="foundations-randomization.html#observed-statistic-vs.-null-statistics"><i class="fa fa-check"></i><b>9.1.3</b> Observed statistic vs. null statistics</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="foundations-randomization.html"><a href="foundations-randomization.html#caseStudySexDiscrimination"><i class="fa fa-check"></i><b>9.2</b> Case study: Sex discrimination</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="foundations-randomization.html"><a href="foundations-randomization.html#observed-data-1"><i class="fa fa-check"></i><b>9.2.1</b> Observed data</a></li>
<li class="chapter" data-level="9.2.2" data-path="foundations-randomization.html"><a href="foundations-randomization.html#variability-of-the-statistic"><i class="fa fa-check"></i><b>9.2.2</b> Variability of the statistic</a></li>
<li class="chapter" data-level="9.2.3" data-path="foundations-randomization.html"><a href="foundations-randomization.html#observed-statistic-vs.-null-statistics-1"><i class="fa fa-check"></i><b>9.2.3</b> Observed statistic vs. null statistics</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="foundations-randomization.html"><a href="foundations-randomization.html#HypothesisTesting"><i class="fa fa-check"></i><b>9.3</b> Hypothesis testing</a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="foundations-randomization.html"><a href="foundations-randomization.html#the-us-court-system"><i class="fa fa-check"></i><b>9.3.1</b> The US court system</a></li>
<li class="chapter" data-level="9.3.2" data-path="foundations-randomization.html"><a href="foundations-randomization.html#p-value-stat-signif"><i class="fa fa-check"></i><b>9.3.2</b> p-value and statistical significance</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="foundations-randomization.html"><a href="foundations-randomization.html#chp9-review"><i class="fa fa-check"></i><b>9.4</b> Chapter review</a>
<ul>
<li class="chapter" data-level="" data-path="foundations-randomization.html"><a href="foundations-randomization.html#summary-6"><i class="fa fa-check"></i>Summary</a></li>
<li class="chapter" data-level="" data-path="foundations-randomization.html"><a href="foundations-randomization.html#terms-7"><i class="fa fa-check"></i>Terms</a></li>
<li class="chapter" data-level="" data-path="foundations-randomization.html"><a href="foundations-randomization.html#key-ideas-6"><i class="fa fa-check"></i>Key ideas</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="foundations-bootstrapping.html"><a href="foundations-bootstrapping.html"><i class="fa fa-check"></i><b>10</b> Confidence intervals with bootstrapping</a>
<ul>
<li class="chapter" data-level="10.1" data-path="foundations-bootstrapping.html"><a href="foundations-bootstrapping.html#case-study-med-consult"><i class="fa fa-check"></i><b>10.1</b> Case study: Medical consultant</a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="foundations-bootstrapping.html"><a href="foundations-bootstrapping.html#observed-data-2"><i class="fa fa-check"></i><b>10.1.1</b> Observed data</a></li>
<li class="chapter" data-level="10.1.2" data-path="foundations-bootstrapping.html"><a href="foundations-bootstrapping.html#variability-of-the-statistic-1"><i class="fa fa-check"></i><b>10.1.2</b> Variability of the statistic</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="foundations-bootstrapping.html"><a href="foundations-bootstrapping.html#ConfidenceIntervals"><i class="fa fa-check"></i><b>10.2</b> Confidence intervals</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="foundations-bootstrapping.html"><a href="foundations-bootstrapping.html#plausible-range-of-values-for-the-population-parameter"><i class="fa fa-check"></i><b>10.2.1</b> Plausible range of values for the population parameter</a></li>
<li class="chapter" data-level="10.2.2" data-path="foundations-bootstrapping.html"><a href="foundations-bootstrapping.html#bootstrap-confidence-interval"><i class="fa fa-check"></i><b>10.2.2</b> Bootstrap confidence interval</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="foundations-bootstrapping.html"><a href="foundations-bootstrapping.html#chp10-review"><i class="fa fa-check"></i><b>10.3</b> Chapter review</a>
<ul>
<li class="chapter" data-level="" data-path="foundations-bootstrapping.html"><a href="foundations-bootstrapping.html#terms-8"><i class="fa fa-check"></i>Terms</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="foundations-mathematical.html"><a href="foundations-mathematical.html"><i class="fa fa-check"></i><b>11</b> Inference with mathematical models</a>
<ul>
<li class="chapter" data-level="11.1" data-path="foundations-mathematical.html"><a href="foundations-mathematical.html#CLTsection"><i class="fa fa-check"></i><b>11.1</b> Central Limit Theorem</a></li>
<li class="chapter" data-level="11.2" data-path="foundations-mathematical.html"><a href="foundations-mathematical.html#normal"><i class="fa fa-check"></i><b>11.2</b> Normal distributions</a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="foundations-mathematical.html"><a href="foundations-mathematical.html#normal-distribution-model"><i class="fa fa-check"></i><b>11.2.1</b> Normal distribution model</a></li>
<li class="chapter" data-level="11.2.2" data-path="foundations-mathematical.html"><a href="foundations-mathematical.html#standardizing-with-z-scores"><i class="fa fa-check"></i><b>11.2.2</b> Standardizing with Z-scores</a></li>
<li class="chapter" data-level="11.2.3" data-path="foundations-mathematical.html"><a href="foundations-mathematical.html#normal-probability-calculations-in-r"><i class="fa fa-check"></i><b>11.2.3</b> Normal probability calculations in R</a></li>
<li class="chapter" data-level="11.2.4" data-path="foundations-mathematical.html"><a href="foundations-mathematical.html#normal-probability-examples"><i class="fa fa-check"></i><b>11.2.4</b> Normal probability examples</a></li>
<li class="chapter" data-level="11.2.5" data-path="foundations-mathematical.html"><a href="foundations-mathematical.html#rule"><i class="fa fa-check"></i><b>11.2.5</b> 68-95-99.7 rule</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="foundations-mathematical.html"><a href="foundations-mathematical.html#quantifying-the-variability-of-a-statistic"><i class="fa fa-check"></i><b>11.3</b> Quantifying the variability of a statistic</a>
<ul>
<li class="chapter" data-level="11.3.1" data-path="foundations-mathematical.html"><a href="foundations-mathematical.html#standard-error"><i class="fa fa-check"></i><b>11.3.1</b> Standard error</a></li>
<li class="chapter" data-level="11.3.2" data-path="foundations-mathematical.html"><a href="foundations-mathematical.html#moe"><i class="fa fa-check"></i><b>11.3.2</b> Margin of error</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="foundations-mathematical.html"><a href="foundations-mathematical.html#chp11-review"><i class="fa fa-check"></i><b>11.4</b> Chapter review</a>
<ul>
<li class="chapter" data-level="" data-path="foundations-mathematical.html"><a href="foundations-mathematical.html#terms-9"><i class="fa fa-check"></i>Terms</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="foundations-errors.html"><a href="foundations-errors.html"><i class="fa fa-check"></i><b>12</b> Errors, power, and practical importance</a>
<ul>
<li class="chapter" data-level="12.1" data-path="foundations-errors.html"><a href="foundations-errors.html#decerr"><i class="fa fa-check"></i><b>12.1</b> Decision errors</a></li>
<li class="chapter" data-level="12.2" data-path="foundations-errors.html"><a href="foundations-errors.html#significance-level"><i class="fa fa-check"></i><b>12.2</b> Significance level</a></li>
<li class="chapter" data-level="12.3" data-path="foundations-errors.html"><a href="foundations-errors.html#two-sided-tests"><i class="fa fa-check"></i><b>12.3</b> Two-sided hypotheses</a></li>
<li class="chapter" data-level="12.4" data-path="foundations-errors.html"><a href="foundations-errors.html#controlling-the-type-1-error-rate"><i class="fa fa-check"></i><b>12.4</b> Controlling the Type 1 error rate</a></li>
<li class="chapter" data-level="12.5" data-path="foundations-errors.html"><a href="foundations-errors.html#power"><i class="fa fa-check"></i><b>12.5</b> Power</a></li>
<li class="chapter" data-level="12.6" data-path="foundations-errors.html"><a href="foundations-errors.html#statistical-significance-vs.-practical-importance"><i class="fa fa-check"></i><b>12.6</b> Statistical significance vs. practical importance</a></li>
<li class="chapter" data-level="12.7" data-path="foundations-errors.html"><a href="foundations-errors.html#chp12-review"><i class="fa fa-check"></i><b>12.7</b> Chapter review</a>
<ul>
<li class="chapter" data-level="" data-path="foundations-errors.html"><a href="foundations-errors.html#terms-10"><i class="fa fa-check"></i>Terms</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="foundations-applications.html"><a href="foundations-applications.html"><i class="fa fa-check"></i><b>13</b> Applications: Foundations</a></li>
<li class="part"><span><b>IV Inference for categorical data</b></span></li>
<li class="chapter" data-level="14" data-path="inference-one-prop.html"><a href="inference-one-prop.html"><i class="fa fa-check"></i><b>14</b> Inference for a single proportion</a>
<ul>
<li class="chapter" data-level="14.1" data-path="inference-one-prop.html"><a href="inference-one-prop.html#one-prop-null-boot"><i class="fa fa-check"></i><b>14.1</b> Simulation-based test for <span class="math inline">\(H_0: \pi = \pi_0\)</span></a>
<ul>
<li class="chapter" data-level="" data-path="inference-one-prop.html"><a href="inference-one-prop.html#steps-1-and-2-hypotheses-and-test-statistic"><i class="fa fa-check"></i>Steps 1 and 2: Hypotheses and test statistic</a></li>
<li class="chapter" data-level="" data-path="inference-one-prop.html"><a href="inference-one-prop.html#steps-3-and-4-null-distribution-and-p-value"><i class="fa fa-check"></i>Steps 3 and 4: Null distribution and p-value</a></li>
<li class="chapter" data-level="" data-path="inference-one-prop.html"><a href="inference-one-prop.html#step-5-conclusion-and-scope-of-inference"><i class="fa fa-check"></i>Step 5: Conclusion and scope of inference</a></li>
</ul></li>
<li class="chapter" data-level="14.2" data-path="inference-one-prop.html"><a href="inference-one-prop.html#boot-ci-prop"><i class="fa fa-check"></i><b>14.2</b> Bootstrap confidence interval for <span class="math inline">\(\pi\)</span></a></li>
<li class="chapter" data-level="14.3" data-path="inference-one-prop.html"><a href="inference-one-prop.html#theory-prop"><i class="fa fa-check"></i><b>14.3</b> Theory-based inferential methods for <span class="math inline">\(\pi\)</span></a>
<ul>
<li class="chapter" data-level="14.3.1" data-path="inference-one-prop.html"><a href="inference-one-prop.html#evaluating-the-two-conditions-required-for-modeling-hatp-using-theory-based-methods"><i class="fa fa-check"></i><b>14.3.1</b> Evaluating the two conditions required for modeling <span class="math inline">\(\hat{p}\)</span> using theory-based methods</a></li>
<li class="chapter" data-level="14.3.2" data-path="inference-one-prop.html"><a href="inference-one-prop.html#payday-lenders"><i class="fa fa-check"></i><b>14.3.2</b> Theory-based test for <span class="math inline">\(H_0: \pi = \pi_0\)</span></a></li>
<li class="chapter" data-level="14.3.3" data-path="inference-one-prop.html"><a href="inference-one-prop.html#theory-based-confidence-interval-for-pi"><i class="fa fa-check"></i><b>14.3.3</b> Theory-based confidence interval for <span class="math inline">\(\pi\)</span></a></li>
<li class="chapter" data-level="14.3.4" data-path="inference-one-prop.html"><a href="inference-one-prop.html#violating-conditions"><i class="fa fa-check"></i><b>14.3.4</b> Violating conditions</a></li>
</ul></li>
<li class="chapter" data-level="14.4" data-path="inference-one-prop.html"><a href="inference-one-prop.html#chp14-review"><i class="fa fa-check"></i><b>14.4</b> Chapter review</a>
<ul>
<li class="chapter" data-level="" data-path="inference-one-prop.html"><a href="inference-one-prop.html#terms-11"><i class="fa fa-check"></i>Terms</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="15" data-path="inference-two-props.html"><a href="inference-two-props.html"><i class="fa fa-check"></i><b>15</b> Inference for comparing two proportions</a>
<ul>
<li class="chapter" data-level="15.1" data-path="inference-two-props.html"><a href="inference-two-props.html#two-prop-errors"><i class="fa fa-check"></i><b>15.1</b> Randomization test for <span class="math inline">\(H_0: \pi_1 - \pi_2 = 0\)</span></a>
<ul>
<li class="chapter" data-level="15.1.1" data-path="inference-two-props.html"><a href="inference-two-props.html#cpr"><i class="fa fa-check"></i><b>15.1.1</b> Case study: CPR and blood thinner</a></li>
<li class="chapter" data-level="15.1.2" data-path="inference-two-props.html"><a href="inference-two-props.html#caseStudyOpportunityCost"><i class="fa fa-check"></i><b>15.1.2</b> Case study: Opportunity cost</a></li>
<li class="chapter" data-level="15.1.3" data-path="inference-two-props.html"><a href="inference-two-props.html#caseStudyMalaria"><i class="fa fa-check"></i><b>15.1.3</b> Case study: Malaria vaccine</a></li>
</ul></li>
<li class="chapter" data-level="15.2" data-path="inference-two-props.html"><a href="inference-two-props.html#two-prop-boot-ci"><i class="fa fa-check"></i><b>15.2</b> Bootstrap confidence interval for <span class="math inline">\(\pi_1 - \pi_2\)</span></a>
<ul>
<li class="chapter" data-level="15.2.1" data-path="inference-two-props.html"><a href="inference-two-props.html#observed-data-3"><i class="fa fa-check"></i><b>15.2.1</b> Observed data</a></li>
<li class="chapter" data-level="15.2.2" data-path="inference-two-props.html"><a href="inference-two-props.html#variability-of-the-statistic-2"><i class="fa fa-check"></i><b>15.2.2</b> Variability of the statistic</a></li>
<li class="chapter" data-level="15.2.3" data-path="inference-two-props.html"><a href="inference-two-props.html#what-does-95-mean"><i class="fa fa-check"></i><b>15.2.3</b> What does 95% mean?</a></li>
</ul></li>
<li class="chapter" data-level="15.3" data-path="inference-two-props.html"><a href="inference-two-props.html#math-2prop"><i class="fa fa-check"></i><b>15.3</b> Theory-based inferential methods for <span class="math inline">\(\pi_1 - \pi_2\)</span></a>
<ul>
<li class="chapter" data-level="15.3.1" data-path="inference-two-props.html"><a href="inference-two-props.html#evaluating-the-two-conditions-required-for-modeling-pi_1---pi_2-using-theory-based-methods"><i class="fa fa-check"></i><b>15.3.1</b> Evaluating the two conditions required for modeling <span class="math inline">\(\pi_1 - \pi_2\)</span> using theory-based methods</a></li>
<li class="chapter" data-level="15.3.2" data-path="inference-two-props.html"><a href="inference-two-props.html#confidence-interval-for-pi_1---pi_2"><i class="fa fa-check"></i><b>15.3.2</b> Confidence interval for <span class="math inline">\(\pi_1 - \pi_2\)</span></a></li>
<li class="chapter" data-level="15.3.3" data-path="inference-two-props.html"><a href="inference-two-props.html#hypothesis-test-for-h_0-pi_1---pi_2-0"><i class="fa fa-check"></i><b>15.3.3</b> Hypothesis test for <span class="math inline">\(H_0: \pi_1 - \pi_2 = 0\)</span></a></li>
</ul></li>
<li class="chapter" data-level="15.4" data-path="inference-two-props.html"><a href="inference-two-props.html#chp15-review"><i class="fa fa-check"></i><b>15.4</b> Chapter review</a>
<ul>
<li class="chapter" data-level="15.4.1" data-path="inference-two-props.html"><a href="inference-two-props.html#summary-of-z-procedures"><i class="fa fa-check"></i><b>15.4.1</b> Summary of Z-procedures</a></li>
<li class="chapter" data-level="" data-path="inference-two-props.html"><a href="inference-two-props.html#terms-12"><i class="fa fa-check"></i>Terms</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="16" data-path="inference-categ-applications.html"><a href="inference-categ-applications.html"><i class="fa fa-check"></i><b>16</b> Applications: Infer categorical</a>
<ul>
<li class="chapter" data-level="" data-path="inference-categ-applications.html"><a href="inference-categ-applications.html#making-tables-from-raw-data"><i class="fa fa-check"></i>Making tables from raw data</a>
<ul>
<li class="chapter" data-level="" data-path="inference-categ-applications.html"><a href="inference-categ-applications.html#simulation-based-inference-for-one-proportion"><i class="fa fa-check"></i>Simulation-based inference for one proportion</a></li>
<li class="chapter" data-level="" data-path="inference-categ-applications.html"><a href="inference-categ-applications.html#simulation-based-inference-for-difference-in-two-proportions"><i class="fa fa-check"></i>Simulation-based inference for difference in two proportions</a></li>
<li class="chapter" data-level="" data-path="inference-categ-applications.html"><a href="inference-categ-applications.html#simulation-based-inference-for-relative-risk"><i class="fa fa-check"></i>Simulation-based inference for relative risk</a></li>
<li class="chapter" data-level="" data-path="inference-categ-applications.html"><a href="inference-categ-applications.html#theory-based-inference-for-one-proportion"><i class="fa fa-check"></i>Theory-based inference for one proportion</a></li>
<li class="chapter" data-level="" data-path="inference-categ-applications.html"><a href="inference-categ-applications.html#theory-based-inference-for-a-difference-in-two-proportions"><i class="fa fa-check"></i>Theory-based inference for a difference in two proportions</a></li>
</ul></li>
<li class="chapter" data-level="16.1" data-path="inference-categ-applications.html"><a href="inference-categ-applications.html#catstats-function-summary"><i class="fa fa-check"></i><b>16.1</b> <code>catstats</code> function summary</a></li>
</ul></li>
<li class="part"><span><b>V Inference for quantitative data</b></span></li>
<li class="chapter" data-level="17" data-path="inference-one-mean.html"><a href="inference-one-mean.html"><i class="fa fa-check"></i><b>17</b> Inference for a single mean</a>
<ul>
<li class="chapter" data-level="17.1" data-path="inference-one-mean.html"><a href="inference-one-mean.html#bootstrap-confidence-interval-for-mu"><i class="fa fa-check"></i><b>17.1</b> Bootstrap confidence interval for <span class="math inline">\(\mu\)</span></a>
<ul>
<li class="chapter" data-level="17.1.1" data-path="inference-one-mean.html"><a href="inference-one-mean.html#observed-data-4"><i class="fa fa-check"></i><b>17.1.1</b> Observed data</a></li>
<li class="chapter" data-level="17.1.2" data-path="inference-one-mean.html"><a href="inference-one-mean.html#variability-of-the-statistic-3"><i class="fa fa-check"></i><b>17.1.2</b> Variability of the statistic</a></li>
<li class="chapter" data-level="17.1.3" data-path="inference-one-mean.html"><a href="inference-one-mean.html#bootstrap-percentile-confidence-interval-for-sigma-special-topic"><i class="fa fa-check"></i><b>17.1.3</b> Bootstrap percentile confidence interval for <span class="math inline">\(\sigma\)</span> (special topic)</a></li>
<li class="chapter" data-level="17.1.4" data-path="inference-one-mean.html"><a href="inference-one-mean.html#bootstrapping-is-not-a-solution-to-small-sample-sizes"><i class="fa fa-check"></i><b>17.1.4</b> Bootstrapping is not a solution to small sample sizes!</a></li>
</ul></li>
<li class="chapter" data-level="17.2" data-path="inference-one-mean.html"><a href="inference-one-mean.html#one-mean-null-boot"><i class="fa fa-check"></i><b>17.2</b> Shifted bootstrap test for <span class="math inline">\(H_0: \mu = \mu_0\)</span></a>
<ul>
<li class="chapter" data-level="17.2.1" data-path="inference-one-mean.html"><a href="inference-one-mean.html#observed-data-5"><i class="fa fa-check"></i><b>17.2.1</b> Observed data</a></li>
<li class="chapter" data-level="17.2.2" data-path="inference-one-mean.html"><a href="inference-one-mean.html#shifted-bootstrapped-null-distribution"><i class="fa fa-check"></i><b>17.2.2</b> Shifted bootstrapped null distribution</a></li>
</ul></li>
<li class="chapter" data-level="17.3" data-path="inference-one-mean.html"><a href="inference-one-mean.html#one-mean-math"><i class="fa fa-check"></i><b>17.3</b> Theory-based inferential methods for <span class="math inline">\(\mu\)</span></a>
<ul>
<li class="chapter" data-level="17.3.1" data-path="inference-one-mean.html"><a href="inference-one-mean.html#evaluating-the-two-conditions-required-for-modeling-bary-using-theory-based-methods"><i class="fa fa-check"></i><b>17.3.1</b> Evaluating the two conditions required for modeling <span class="math inline">\(\bar{y}\)</span> using theory-based methods</a></li>
<li class="chapter" data-level="17.3.2" data-path="inference-one-mean.html"><a href="inference-one-mean.html#introducing-the-t-distribution"><i class="fa fa-check"></i><b>17.3.2</b> Introducing the <span class="math inline">\(t\)</span>-distribution</a></li>
<li class="chapter" data-level="17.3.3" data-path="inference-one-mean.html"><a href="inference-one-mean.html#one-sample-t-confidence-intervals"><i class="fa fa-check"></i><b>17.3.3</b> One sample <span class="math inline">\(t\)</span>-confidence intervals</a></li>
<li class="chapter" data-level="17.3.4" data-path="inference-one-mean.html"><a href="inference-one-mean.html#one-sample-t-tests"><i class="fa fa-check"></i><b>17.3.4</b> One sample <span class="math inline">\(t\)</span>-tests</a></li>
</ul></li>
<li class="chapter" data-level="17.4" data-path="inference-one-mean.html"><a href="inference-one-mean.html#chp17-review"><i class="fa fa-check"></i><b>17.4</b> Chapter review</a>
<ul>
<li class="chapter" data-level="" data-path="inference-one-mean.html"><a href="inference-one-mean.html#terms-13"><i class="fa fa-check"></i>Terms</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="18" data-path="inference-paired-means.html"><a href="inference-paired-means.html"><i class="fa fa-check"></i><b>18</b> Inference for comparing paired means</a>
<ul>
<li class="chapter" data-level="18.1" data-path="inference-paired-means.html"><a href="inference-paired-means.html#shifted-bootstrap-test-for-h_0-mu_d-0"><i class="fa fa-check"></i><b>18.1</b> Shifted bootstrap test for <span class="math inline">\(H_0: \mu_d = 0\)</span></a>
<ul>
<li class="chapter" data-level="18.1.1" data-path="inference-paired-means.html"><a href="inference-paired-means.html#observed-data-7"><i class="fa fa-check"></i><b>18.1.1</b> Observed data</a></li>
<li class="chapter" data-level="18.1.2" data-path="inference-paired-means.html"><a href="inference-paired-means.html#variability-of-the-statistic-4"><i class="fa fa-check"></i><b>18.1.2</b> Variability of the statistic</a></li>
<li class="chapter" data-level="18.1.3" data-path="inference-paired-means.html"><a href="inference-paired-means.html#observed-statistic-vs.-null-value"><i class="fa fa-check"></i><b>18.1.3</b> Observed statistic vs. null value</a></li>
</ul></li>
<li class="chapter" data-level="18.2" data-path="inference-paired-means.html"><a href="inference-paired-means.html#bootstrap-confidence-interval-for-mu_d"><i class="fa fa-check"></i><b>18.2</b> Bootstrap confidence interval for <span class="math inline">\(\mu_d\)</span></a>
<ul>
<li class="chapter" data-level="18.2.1" data-path="inference-paired-means.html"><a href="inference-paired-means.html#observed-data-8"><i class="fa fa-check"></i><b>18.2.1</b> Observed data</a></li>
<li class="chapter" data-level="18.2.2" data-path="inference-paired-means.html"><a href="inference-paired-means.html#variability-of-the-statistic-5"><i class="fa fa-check"></i><b>18.2.2</b> Variability of the statistic</a></li>
</ul></li>
<li class="chapter" data-level="18.3" data-path="inference-paired-means.html"><a href="inference-paired-means.html#paired-mean-math"><i class="fa fa-check"></i><b>18.3</b> Theory-based inferential methods for <span class="math inline">\(\mu_d\)</span></a>
<ul>
<li class="chapter" data-level="18.3.1" data-path="inference-paired-means.html"><a href="inference-paired-means.html#observed-data-9"><i class="fa fa-check"></i><b>18.3.1</b> Observed data</a></li>
<li class="chapter" data-level="18.3.2" data-path="inference-paired-means.html"><a href="inference-paired-means.html#variability-of-the-statistic-6"><i class="fa fa-check"></i><b>18.3.2</b> Variability of the statistic</a></li>
<li class="chapter" data-level="18.3.3" data-path="inference-paired-means.html"><a href="inference-paired-means.html#observed-statistic-vs.-null-statistics-2"><i class="fa fa-check"></i><b>18.3.3</b> Observed statistic vs. null statistics</a></li>
</ul></li>
<li class="chapter" data-level="18.4" data-path="inference-paired-means.html"><a href="inference-paired-means.html#chp18-review"><i class="fa fa-check"></i><b>18.4</b> Chapter review</a>
<ul>
<li class="chapter" data-level="" data-path="inference-paired-means.html"><a href="inference-paired-means.html#terms-14"><i class="fa fa-check"></i>Terms</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="19" data-path="inference-two-means.html"><a href="inference-two-means.html"><i class="fa fa-check"></i><b>19</b> Inference for comparing two independent means</a>
<ul>
<li class="chapter" data-level="19.1" data-path="inference-two-means.html"><a href="inference-two-means.html#rand2mean"><i class="fa fa-check"></i><b>19.1</b> Randomization test for <span class="math inline">\(H_0: \mu_1 - \mu_2 = 0\)</span></a>
<ul>
<li class="chapter" data-level="19.1.1" data-path="inference-two-means.html"><a href="inference-two-means.html#observed-data-10"><i class="fa fa-check"></i><b>19.1.1</b> Observed data</a></li>
<li class="chapter" data-level="19.1.2" data-path="inference-two-means.html"><a href="inference-two-means.html#variability-of-the-statistic-7"><i class="fa fa-check"></i><b>19.1.2</b> Variability of the statistic</a></li>
<li class="chapter" data-level="19.1.3" data-path="inference-two-means.html"><a href="inference-two-means.html#observed-statistic-vs.-null-value-1"><i class="fa fa-check"></i><b>19.1.3</b> Observed statistic vs. null value</a></li>
</ul></li>
<li class="chapter" data-level="19.2" data-path="inference-two-means.html"><a href="inference-two-means.html#boot-ci-diff-means"><i class="fa fa-check"></i><b>19.2</b> Bootstrap confidence interval for <span class="math inline">\(\mu_1 - \mu_2\)</span></a>
<ul>
<li class="chapter" data-level="19.2.1" data-path="inference-two-means.html"><a href="inference-two-means.html#observed-data-11"><i class="fa fa-check"></i><b>19.2.1</b> Observed data</a></li>
<li class="chapter" data-level="19.2.2" data-path="inference-two-means.html"><a href="inference-two-means.html#variability-of-the-statistic-8"><i class="fa fa-check"></i><b>19.2.2</b> Variability of the statistic</a></li>
</ul></li>
<li class="chapter" data-level="19.3" data-path="inference-two-means.html"><a href="inference-two-means.html#math2samp"><i class="fa fa-check"></i><b>19.3</b> Theory-based inferential methods for <span class="math inline">\(\mu_1 - \mu_2\)</span></a>
<ul>
<li class="chapter" data-level="19.3.1" data-path="inference-two-means.html"><a href="inference-two-means.html#t-test-for-mu_1---mu_2"><i class="fa fa-check"></i><b>19.3.1</b> <span class="math inline">\(t\)</span>-test for <span class="math inline">\(\mu_1 - \mu_2\)</span></a></li>
<li class="chapter" data-level="19.3.2" data-path="inference-two-means.html"><a href="inference-two-means.html#t-confidence-interval-for-mu_1---mu_2"><i class="fa fa-check"></i><b>19.3.2</b> <span class="math inline">\(t\)</span> confidence interval for <span class="math inline">\(\mu_1 - \mu_2\)</span></a></li>
</ul></li>
<li class="chapter" data-level="19.4" data-path="inference-two-means.html"><a href="inference-two-means.html#chp19-review"><i class="fa fa-check"></i><b>19.4</b> Chapter review</a>
<ul>
<li class="chapter" data-level="" data-path="inference-two-means.html"><a href="inference-two-means.html#summary-of-t-procedures"><i class="fa fa-check"></i>Summary of t-procedures</a></li>
<li class="chapter" data-level="" data-path="inference-two-means.html"><a href="inference-two-means.html#terms-15"><i class="fa fa-check"></i>Terms</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="20" data-path="inference-num-applications.html"><a href="inference-num-applications.html"><i class="fa fa-check"></i><b>20</b> Applications: Infer quantitative</a>
<ul>
<li class="chapter" data-level="20.1" data-path="inference-num-applications.html"><a href="inference-num-applications.html#inference-for-quantitative-data-using-r-and-catstats"><i class="fa fa-check"></i><b>20.1</b> Inference for quantitative data using R and <code>catstats</code></a>
<ul>
<li class="chapter" data-level="" data-path="inference-num-applications.html"><a href="inference-num-applications.html#using-the-t-distribution"><i class="fa fa-check"></i>Using the <span class="math inline">\(t\)</span>-distribution</a></li>
<li class="chapter" data-level="" data-path="inference-num-applications.html"><a href="inference-num-applications.html#simulation-based-inference-for-paired-mean-difference"><i class="fa fa-check"></i>Simulation-based inference for paired mean difference</a></li>
<li class="chapter" data-level="" data-path="inference-num-applications.html"><a href="inference-num-applications.html#theory-based-inference-for-paired-mean-difference"><i class="fa fa-check"></i>Theory-based inference for paired mean difference</a></li>
<li class="chapter" data-level="" data-path="inference-num-applications.html"><a href="inference-num-applications.html#simulation-based-inference-for-the-difference-of-two-means"><i class="fa fa-check"></i>Simulation-based inference for the difference of two means</a></li>
<li class="chapter" data-level="" data-path="inference-num-applications.html"><a href="inference-num-applications.html#theory-based-inference-for-the-difference-of-two-means"><i class="fa fa-check"></i>Theory-based inference for the difference of two means</a></li>
</ul></li>
<li class="chapter" data-level="20.2" data-path="inference-num-applications.html"><a href="inference-num-applications.html#catstats-function-summary-1"><i class="fa fa-check"></i><b>20.2</b> <code>catstats</code> function summary</a></li>
</ul></li>
<li class="part"><span><b>VI Inference for regression</b></span></li>
<li class="chapter" data-level="21" data-path="inference-reg.html"><a href="inference-reg.html"><i class="fa fa-check"></i><b>21</b> Inference for correlation and slope</a>
<ul>
<li class="chapter" data-level="21.1" data-path="inference-reg.html"><a href="inference-reg.html#case-study-sandwich-store"><i class="fa fa-check"></i><b>21.1</b> Case study: Sandwich store</a>
<ul>
<li class="chapter" data-level="21.1.1" data-path="inference-reg.html"><a href="inference-reg.html#observed-data-13"><i class="fa fa-check"></i><b>21.1.1</b> Observed data</a></li>
<li class="chapter" data-level="21.1.2" data-path="inference-reg.html"><a href="inference-reg.html#variability-of-the-statistic-10"><i class="fa fa-check"></i><b>21.1.2</b> Variability of the statistic</a></li>
</ul></li>
<li class="chapter" data-level="21.2" data-path="inference-reg.html"><a href="inference-reg.html#randslope"><i class="fa fa-check"></i><b>21.2</b> Randomization test for <span class="math inline">\(H_0: \beta_1= 0\)</span></a>
<ul>
<li class="chapter" data-level="21.2.1" data-path="inference-reg.html"><a href="inference-reg.html#observed-data-14"><i class="fa fa-check"></i><b>21.2.1</b> Observed data</a></li>
<li class="chapter" data-level="21.2.2" data-path="inference-reg.html"><a href="inference-reg.html#variability-of-the-statistic-11"><i class="fa fa-check"></i><b>21.2.2</b> Variability of the statistic</a></li>
<li class="chapter" data-level="21.2.3" data-path="inference-reg.html"><a href="inference-reg.html#observed-statistic-vs.-null-value-3"><i class="fa fa-check"></i><b>21.2.3</b> Observed statistic vs. null value</a></li>
</ul></li>
<li class="chapter" data-level="21.3" data-path="inference-reg.html"><a href="inference-reg.html#bootbeta1"><i class="fa fa-check"></i><b>21.3</b> Bootstrap confidence interval for <span class="math inline">\(\beta_1\)</span></a>
<ul>
<li class="chapter" data-level="21.3.1" data-path="inference-reg.html"><a href="inference-reg.html#observed-data-15"><i class="fa fa-check"></i><b>21.3.1</b> Observed data</a></li>
<li class="chapter" data-level="21.3.2" data-path="inference-reg.html"><a href="inference-reg.html#variability-of-the-statistic-12"><i class="fa fa-check"></i><b>21.3.2</b> Variability of the statistic</a></li>
</ul></li>
<li class="chapter" data-level="21.4" data-path="inference-reg.html"><a href="inference-reg.html#inference-on-the-correlation-coefficient-rho"><i class="fa fa-check"></i><b>21.4</b> Inference on the correlation coefficient <span class="math inline">\(\rho\)</span></a></li>
<li class="chapter" data-level="21.5" data-path="inference-reg.html"><a href="inference-reg.html#mathslope"><i class="fa fa-check"></i><b>21.5</b> Theory-based inferential methods for <span class="math inline">\(\beta_1\)</span></a>
<ul>
<li class="chapter" data-level="21.5.1" data-path="inference-reg.html"><a href="inference-reg.html#case-study-midterm-elections-and-unemployment"><i class="fa fa-check"></i><b>21.5.1</b> Case study: Midterm elections and unemployment</a></li>
<li class="chapter" data-level="21.5.2" data-path="inference-reg.html"><a href="inference-reg.html#understanding-regression-output-from-software"><i class="fa fa-check"></i><b>21.5.2</b> Understanding regression output from software</a></li>
<li class="chapter" data-level="21.5.3" data-path="inference-reg.html"><a href="inference-reg.html#intuition-vs.-formal-inference"><i class="fa fa-check"></i><b>21.5.3</b> Intuition vs. formal inference</a></li>
<li class="chapter" data-level="21.5.4" data-path="inference-reg.html"><a href="inference-reg.html#theory-based-confidence-interval-for-a-regression-coefficient"><i class="fa fa-check"></i><b>21.5.4</b> Theory-based confidence interval for a regression coefficient</a></li>
</ul></li>
<li class="chapter" data-level="21.6" data-path="inference-reg.html"><a href="inference-reg.html#tech-cond-linmod"><i class="fa fa-check"></i><b>21.6</b> Checking model conditions</a>
<ul>
<li class="chapter" data-level="21.6.1" data-path="inference-reg.html"><a href="inference-reg.html#linearity"><i class="fa fa-check"></i><b>21.6.1</b> <strong>L</strong>inearity</a></li>
<li class="chapter" data-level="21.6.2" data-path="inference-reg.html"><a href="inference-reg.html#independence"><i class="fa fa-check"></i><b>21.6.2</b> <strong>I</strong>ndependence</a></li>
<li class="chapter" data-level="21.6.3" data-path="inference-reg.html"><a href="inference-reg.html#normality"><i class="fa fa-check"></i><b>21.6.3</b> <strong>N</strong>ormality</a></li>
<li class="chapter" data-level="21.6.4" data-path="inference-reg.html"><a href="inference-reg.html#equal-variability"><i class="fa fa-check"></i><b>21.6.4</b> <strong>E</strong>qual variability</a></li>
<li class="chapter" data-level="21.6.5" data-path="inference-reg.html"><a href="inference-reg.html#scope-of-inference-for-regression"><i class="fa fa-check"></i><b>21.6.5</b> Scope of Inference for Regression</a></li>
</ul></li>
<li class="chapter" data-level="21.7" data-path="inference-reg.html"><a href="inference-reg.html#chp21-review"><i class="fa fa-check"></i><b>21.7</b> Chapter review</a>
<ul>
<li class="chapter" data-level="" data-path="inference-reg.html"><a href="inference-reg.html#terms-16"><i class="fa fa-check"></i>Terms</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="22" data-path="inference-reg-applications.html"><a href="inference-reg-applications.html"><i class="fa fa-check"></i><b>22</b> Applications: Infer regression</a>
<ul>
<li class="chapter" data-level="22.1" data-path="inference-reg-applications.html"><a href="inference-reg-applications.html#inference-for-regression-using-r-and-catstats"><i class="fa fa-check"></i><b>22.1</b> Inference for regression using R and <code>catstats</code></a>
<ul>
<li class="chapter" data-level="" data-path="inference-reg-applications.html"><a href="inference-reg-applications.html#simulation-based-inference-for-the-regression-slope"><i class="fa fa-check"></i>Simulation-based inference for the regression slope</a></li>
<li class="chapter" data-level="" data-path="inference-reg-applications.html"><a href="inference-reg-applications.html#theory-based-inference-for-the-regression-slope"><i class="fa fa-check"></i>Theory-based inference for the regression slope</a></li>
</ul></li>
<li class="chapter" data-level="22.2" data-path="inference-reg-applications.html"><a href="inference-reg-applications.html#catstats-function-summary-2"><i class="fa fa-check"></i><b>22.2</b> <code>catstats</code> function summary</a></li>
</ul></li>
<li class="part"><span><b>VII Probability</b></span></li>
<li class="chapter" data-level="23" data-path="probability.html"><a href="probability.html"><i class="fa fa-check"></i><b>23</b> Probability with tables</a>
<ul>
<li class="chapter" data-level="23.1" data-path="probability.html"><a href="probability.html#defining-probability"><i class="fa fa-check"></i><b>23.1</b> Defining probability</a></li>
<li class="chapter" data-level="23.2" data-path="probability.html"><a href="probability.html#finding-probabilities-with-tables"><i class="fa fa-check"></i><b>23.2</b> Finding probabilities with tables</a></li>
<li class="chapter" data-level="23.3" data-path="probability.html"><a href="probability.html#probability-notation"><i class="fa fa-check"></i><b>23.3</b> Probability notation</a></li>
<li class="chapter" data-level="23.4" data-path="probability.html"><a href="probability.html#diagnostic-testing"><i class="fa fa-check"></i><b>23.4</b> Diagnostic testing</a>
<ul>
<li class="chapter" data-level="23.4.1" data-path="probability.html"><a href="probability.html#the-case-of-baby-jeff"><i class="fa fa-check"></i><b>23.4.1</b> The case of Baby Jeff</a></li>
</ul></li>
<li class="chapter" data-level="23.5" data-path="probability.html"><a href="probability.html#chp23-review"><i class="fa fa-check"></i><b>23.5</b> Chapter review</a>
<ul>
<li class="chapter" data-level="" data-path="probability.html"><a href="probability.html#terms-17"><i class="fa fa-check"></i>Terms</a></li>
<li class="chapter" data-level="" data-path="probability.html"><a href="probability.html#key-ideas-7"><i class="fa fa-check"></i>Key ideas</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Montana State Introductory Statistics with R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="inference-categ-applications" class="section level1 hasAnchor" number="16">
<h1><span class="header-section-number">Chapter 16</span> Applications: Infer categorical<a href="inference-categ-applications.html#inference-categ-applications" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div class="chapterintro">
<p>In this chapter, we will explore how to conduct statistical inference for categorical variables using the <code>catstats</code> package in RStudio. Review the <a href="rstudio">Preliminaries</a> Chapter for instructions for installing <code>catstats</code>.
We encourage you to work through the code in this chapter in
your own RStudio session.</p>
</div>
<p>Much of the R code we use below is from the <code>tidyverse</code> R package. Load this package and the <code>catstats</code> package prior to running the code in this chapter.</p>
<div id="making-tables-from-raw-data" class="section level2 unnumbered hasAnchor">
<h2>Making tables from raw data<a href="inference-categ-applications.html#making-tables-from-raw-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>If you are collecting your own data, then your analysis starts with the raw data frame, with one observational unit per row and one variable per column. In this case, you first need to find counts (frequencies) of observations in each category prior to inference. We can use the <code>table()</code> function in R on the raw data to create a contingency table of the counts for each categorical variable.</p>
<p>In the one-proportion case, suppose we have a data frame called <code>loans</code> with a variable <code>regulate</code> that contains the Yes/No response of the 826 payday loan borrowers from Section <a href="inference-one-prop.html#payday-lenders">14.3.2</a> regarding their support for a regulation to require lenders to pull their credit report and evaluate their debt payments. Run the following line of code to create this data set in RStudio.</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="inference-categ-applications.html#cb28-1" tabindex="-1"></a>loans <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">regulate =</span> <span class="fu">sample</span>(<span class="fu">c</span>(<span class="fu">rep</span>(<span class="st">&quot;Yes&quot;</span>, <span class="dv">422</span>), <span class="fu">rep</span>(<span class="st">&quot;No&quot;</span>, <span class="dv">404</span>))))</span></code></pre></div>
<p>We can obtain counts of borrowers for each response using the <code>count()</code> function in R:</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="inference-categ-applications.html#cb29-1" tabindex="-1"></a><span class="fu">table</span>(loans<span class="sc">$</span>regulate)</span></code></pre></div>
<pre><code>#&gt; 
#&gt;  No Yes 
#&gt; 404 422</code></pre>
<p>In the R code above, <code>loans</code> is the name of the data set in R, and <code>regulate</code> is the name of the variable. The <code>$</code> tells R to select the <code>regulate</code> variable from the <code>loans</code> data set. We could have also used the pipe command to generate the table:</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="inference-categ-applications.html#cb31-1" tabindex="-1"></a>loans <span class="sc">%&gt;%</span> <span class="fu">select</span>(regulate) <span class="sc">%&gt;%</span> <span class="fu">table</span>()</span></code></pre></div>
<pre><code>#&gt; regulate
#&gt;  No Yes 
#&gt; 404 422</code></pre>
<p>We can also use <code>table()</code> to compute the proportions in each group by dividing by the number of observations:</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="inference-categ-applications.html#cb33-1" tabindex="-1"></a><span class="co">#If we know the number of observations:</span></span>
<span id="cb33-2"><a href="inference-categ-applications.html#cb33-2" tabindex="-1"></a><span class="fu">table</span>(loans<span class="sc">$</span>regulate)<span class="sc">/</span><span class="dv">826</span></span></code></pre></div>
<pre><code>#&gt; 
#&gt;    No   Yes 
#&gt; 0.489 0.511</code></pre>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="inference-categ-applications.html#cb35-1" tabindex="-1"></a><span class="co">#If we don&#39;t know the number of observations:</span></span>
<span id="cb35-2"><a href="inference-categ-applications.html#cb35-2" tabindex="-1"></a><span class="fu">table</span>(loans<span class="sc">$</span>regulate)<span class="sc">/</span><span class="fu">length</span>(loans<span class="sc">$</span>regulate)</span></code></pre></div>
<pre><code>#&gt; 
#&gt;    No   Yes 
#&gt; 0.489 0.511</code></pre>
<p>For comparisons of two proportions, we get a two-way table. Consider the case study of the effect of blood thinners on survival after receiving CPR from Section <a href="inference-two-props.html#cpr">15.1.1</a>. Data from this study are stored in a data frame called <code>cpr</code>, with variables <code>survival</code> – giving each patient’s outcome decision – and <code>group</code> – indicating whether they were in the treatment (blood thinner) or control (no blood thinner) group. Run the following lines of code to create this data set in RStudio.</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="inference-categ-applications.html#cb37-1" tabindex="-1"></a>survival <span class="ot">&lt;-</span> <span class="fu">factor</span>(<span class="fu">c</span>(<span class="fu">rep</span>(<span class="st">&quot;Survived&quot;</span>, <span class="dv">25</span>), <span class="fu">rep</span>(<span class="st">&quot;Died&quot;</span>, <span class="dv">65</span>)))</span>
<span id="cb37-2"><a href="inference-categ-applications.html#cb37-2" tabindex="-1"></a>group <span class="ot">&lt;-</span> <span class="fu">factor</span>(<span class="fu">rep.int</span>(<span class="fu">c</span>(<span class="st">&quot;control&quot;</span>, <span class="st">&quot;treatment&quot;</span>, <span class="st">&quot;control&quot;</span>, <span class="st">&quot;treatment&quot;</span>), <span class="at">times =</span> <span class="fu">c</span>(<span class="dv">11</span>, <span class="dv">14</span>, <span class="dv">39</span>, <span class="dv">26</span>)))</span>
<span id="cb37-3"><a href="inference-categ-applications.html#cb37-3" tabindex="-1"></a></span>
<span id="cb37-4"><a href="inference-categ-applications.html#cb37-4" tabindex="-1"></a>cpr <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(survival, group)</span></code></pre></div>
<p>The <code>glimpse()</code> and <code>summary()</code> functions can help us see what variables are in our data set and the values they take on:</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="inference-categ-applications.html#cb38-1" tabindex="-1"></a><span class="fu">glimpse</span>(cpr)</span></code></pre></div>
<pre><code>#&gt; Rows: 90
#&gt; Columns: 2
#&gt; $ survival &lt;fct&gt; Survived, Survived, Survived, Survived, Survived, Survived, S…
#&gt; $ group    &lt;fct&gt; control, control, control, control, control, control, control…</code></pre>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="inference-categ-applications.html#cb40-1" tabindex="-1"></a><span class="fu">summary</span>(cpr)</span></code></pre></div>
<pre><code>#&gt;      survival        group   
#&gt;  Died    :65   control  :50  
#&gt;  Survived:25   treatment:40</code></pre>
<p>To obtain the two-way table of the choices by group, we again use the <code>table()</code> function in R. The key thing to remember here is to put the response variable (outcome) as the first argument and the explanatory variable (grouping) as the second. In our example, <code>survival</code> is the response variable, and <code>group</code> is the explanatory variable.</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="inference-categ-applications.html#cb42-1" tabindex="-1"></a><span class="fu">table</span>(cpr<span class="sc">$</span>survival, cpr<span class="sc">$</span>group)</span></code></pre></div>
<pre><code>#&gt;           
#&gt;            control treatment
#&gt;   Died          39        26
#&gt;   Survived      11        14</code></pre>
<p>This will set up the table to be useful for making segmented bar plots and using column percentages to compute test statistics. In order to do either of these things, we need to store the table in an R object so we can manipulate it further:</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="inference-categ-applications.html#cb44-1" tabindex="-1"></a>data_tbl <span class="ot">&lt;-</span> <span class="fu">table</span>(cpr<span class="sc">$</span>survival, cpr<span class="sc">$</span>group)</span></code></pre></div>
<p>To get column percentages, we use the <code>prop.table()</code> function:</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="inference-categ-applications.html#cb45-1" tabindex="-1"></a><span class="fu">prop.table</span>(data_tbl,  <span class="co">#Feed in your two-way table</span></span>
<span id="cb45-2"><a href="inference-categ-applications.html#cb45-2" tabindex="-1"></a>           <span class="at">margin =</span> <span class="dv">2</span>)  <span class="co">#Tell it to compute percentages for columns</span></span></code></pre></div>
<pre><code>#&gt;           
#&gt;            control treatment
#&gt;   Died        0.78      0.65
#&gt;   Survived    0.22      0.35</code></pre>
<!-- #### Making tables from counts {-} -->
<!-- If you don't have access to the raw data, and only have access to the two-way table itself, you can create this table in R with the `as.table` function. -->
<div id="simulation-based-inference-for-one-proportion" class="section level3 unnumbered hasAnchor">
<h3>Simulation-based inference for one proportion<a href="inference-categ-applications.html#simulation-based-inference-for-one-proportion" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>For simulation-based inference, we will use functions included in the <code>catstats</code> package, created for MSU Statistics courses. See the <a href="#stat-computing">Statistical computing</a> section at the beginning of this textbook for instructions on how to install <code>catstats</code> if you haven’t already. If the package is installed, you can load it into an R session to make the functions available using the <code>library()</code> function:</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="inference-categ-applications.html#cb47-1" tabindex="-1"></a><span class="fu">library</span>(catstats)</span></code></pre></div>
<p>Once you have loaded the package, you will be able to use the functions for simulation-based inference. For one-proportion inference, this is the <code>one_proportion_test()</code> function and <code>one_proportion_bootstrap_CI()</code> function. Returning to the payday loan regulation example, we can obtain a simulation distribution and p-value using the following function call:</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="inference-categ-applications.html#cb48-1" tabindex="-1"></a><span class="fu">one_proportion_test</span>(</span>
<span id="cb48-2"><a href="inference-categ-applications.html#cb48-2" tabindex="-1"></a>  <span class="at">probability_success =</span> <span class="fl">0.5</span>, <span class="co">#null hypothesis probability of success</span></span>
<span id="cb48-3"><a href="inference-categ-applications.html#cb48-3" tabindex="-1"></a>  <span class="at">sample_size =</span> <span class="dv">826</span>,  <span class="co">#number of observations</span></span>
<span id="cb48-4"><a href="inference-categ-applications.html#cb48-4" tabindex="-1"></a>  <span class="at">number_repetitions =</span> <span class="dv">1000</span>,  <span class="co">#number of simulations to create</span></span>
<span id="cb48-5"><a href="inference-categ-applications.html#cb48-5" tabindex="-1"></a>  <span class="at">as_extreme_as =</span> <span class="fl">0.51</span>,  <span class="co">#observed statistic</span></span>
<span id="cb48-6"><a href="inference-categ-applications.html#cb48-6" tabindex="-1"></a>  <span class="at">direction =</span> <span class="st">&quot;greater&quot;</span>,  <span class="co">#alternative hypothesis direction</span></span>
<span id="cb48-7"><a href="inference-categ-applications.html#cb48-7" tabindex="-1"></a>  <span class="at">summary_measure =</span> <span class="st">&quot;proportion&quot;</span>  <span class="co">#Report number or proportion of successes?</span></span>
<span id="cb48-8"><a href="inference-categ-applications.html#cb48-8" tabindex="-1"></a>)</span></code></pre></div>
<p><img src="16-categorical-applications_files/figure-html/onePropSimInf-1.png" alt="" width="90%" style="display: block; margin: auto;" /></p>
<div class="importantbox">
<p>Note that the observed statistic (<code>as_extreme_as</code>) and the <code>summary_measure</code> input need to match; since we put in the observed statistic as a proportion, we need to tell the function to report the proportion of successes. If they don’t match, you will almost certainly get a p-value of 0 or 1 – this can happen when there is very strong evidence against the null, but it is always good to check your function inputs when you get an extreme outcome to make sure that is what you should be seeing.</p>
</div>
<p>In the resulting graph, we see the null distribution of simulated proportions, with those greater than the observed value of 0.51 highlighted in blue. In the figure caption, we see that 308 of our 1000 simulations resulted in a proportion of successes at least as large as the observed value, yielding an approximate p-value of 0.308.</p>
<p>To find a confidence interval for the true proportion of payday loan borrowers who support the regulation, we use the <code>one_proportion_bootstrap_CI()</code> function:</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="inference-categ-applications.html#cb49-1" tabindex="-1"></a><span class="fu">one_proportion_bootstrap_CI</span>(</span>
<span id="cb49-2"><a href="inference-categ-applications.html#cb49-2" tabindex="-1"></a>  <span class="at">sample_size =</span> <span class="dv">826</span>,  <span class="co">#Number of observations</span></span>
<span id="cb49-3"><a href="inference-categ-applications.html#cb49-3" tabindex="-1"></a>  <span class="at">number_successes =</span> <span class="dv">422</span>,  <span class="co">#Number of observed successes </span></span>
<span id="cb49-4"><a href="inference-categ-applications.html#cb49-4" tabindex="-1"></a>  <span class="at">number_repetitions =</span> <span class="dv">1000</span>,  <span class="co">#Number of bootstrap draws</span></span>
<span id="cb49-5"><a href="inference-categ-applications.html#cb49-5" tabindex="-1"></a>  <span class="at">confidence_level =</span> <span class="fl">0.95</span>  <span class="co">#Confidence level, as a proportion</span></span>
<span id="cb49-6"><a href="inference-categ-applications.html#cb49-6" tabindex="-1"></a>)</span></code></pre></div>
<p><img src="16-categorical-applications_files/figure-html/onePropBootCI-1.png" alt="" width="90%" style="display: block; margin: auto;" /></p>
<p>This produces a plot of the bootstrapped proportions with the upper and lower bounds of the confidence interval marked, and gives the interval itself in the figure caption: in this case, we are 95% confident that the true proportion of payday loan borrowers who support the proposed regulation is between 0.479 and 0.546.</p>
</div>
<div id="simulation-based-inference-for-difference-in-two-proportions" class="section level3 unnumbered hasAnchor">
<h3>Simulation-based inference for difference in two proportions<a href="inference-categ-applications.html#simulation-based-inference-for-difference-in-two-proportions" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>For inference about the difference between two proportions, we use the <code>two_proportion_test()</code> and <code>two_proportion_bootstrap_CI()</code> functions. Before doing doing inference to compare two proportions, you should create a mosaic plot to visualize the sample proportions being compared and to verify the names of the two groups. The response variable should be on the <span class="math inline">\(y\)</span>-axis and the predictor (grouping) variable should be on the <span class="math inline">\(x\)</span>-axis in the mosaic plot, which is accomplished with <code>x = product(group)</code> (for the predictor variable called <code>group</code>) and <code>fill = survival</code> (for the <span class="math inline">\(y\)</span>-axis variable to fill the bars based on the <code>survival</code> of the subjects) here.</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="inference-categ-applications.html#cb50-1" tabindex="-1"></a>cpr <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb50-2"><a href="inference-categ-applications.html#cb50-2" tabindex="-1"></a>  <span class="fu">geom_mosaic</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">product</span>(group), <span class="at">fill =</span> survival)) <span class="sc">+</span></span>
<span id="cb50-3"><a href="inference-categ-applications.html#cb50-3" tabindex="-1"></a>  <span class="fu">scale_fill_colorblind</span>()</span></code></pre></div>
<p><img src="16-categorical-applications_files/figure-html/twopropmosaic-1.png" alt="" width="90%" style="display: block; margin: auto;" />
In using the <code>two_proportion_test()</code> formula, it requires <code>response</code> <span class="math inline">\(\sim\)</span> <code>explanatory</code>. You can check that your formula is correct by using the explanatory (grouping) variable from the <span class="math inline">\(x\)</span>-axis and the response variable from the <span class="math inline">\(y\)</span>-axis in the mosaic plot. The function requires that you declare the order of subtraction between the predictor variable groups using <code>first_in_subtraction</code> to select a level of the grouping variable (“treatment” is selected here) to be first in the comparison on the proportions. The level of the response to use as the “success” (“Survived” is selected here) must also be specified. Additional required options are the <code>number_repetitions</code> (use 10000 unless that is computationally problematic), the value of the observed statistic (difference in proportions here) in <code>as_extreme_as</code>, and the direction of the alternative in <code>direction</code>(choices of <code>two-sided</code>, <code>greater</code>, or <code>less</code>) based on your desired alternative hypothesis. Note that the order of subtraction and success choices impact the direction used for one-sided tests.</p>
<p>Using the CPR and blood thinner study for a two-sided test with an observed difference in proportions of 0.13, a call to <code>two_proportion_test()</code> would look like this:</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="inference-categ-applications.html#cb51-1" tabindex="-1"></a><span class="fu">two_proportion_test</span>(</span>
<span id="cb51-2"><a href="inference-categ-applications.html#cb51-2" tabindex="-1"></a>  <span class="at">formula =</span> survival <span class="sc">~</span> group,  <span class="co">#Always do response ~ explanatory</span></span>
<span id="cb51-3"><a href="inference-categ-applications.html#cb51-3" tabindex="-1"></a>  <span class="at">data =</span> cpr,   <span class="co">#Name of the data set</span></span>
<span id="cb51-4"><a href="inference-categ-applications.html#cb51-4" tabindex="-1"></a>  <span class="at">first_in_subtraction =</span> <span class="st">&quot;treatment&quot;</span>, <span class="co">#Value of the explanatory variable that is first in order of subtraction</span></span>
<span id="cb51-5"><a href="inference-categ-applications.html#cb51-5" tabindex="-1"></a>  <span class="at">response_value_numerator =</span> <span class="st">&quot;Survived&quot;</span>,  <span class="co">#Value of response that is a &quot;success&quot;</span></span>
<span id="cb51-6"><a href="inference-categ-applications.html#cb51-6" tabindex="-1"></a>  <span class="at">number_repetitions =</span> <span class="dv">1000</span>,</span>
<span id="cb51-7"><a href="inference-categ-applications.html#cb51-7" tabindex="-1"></a>  <span class="at">as_extreme_as =</span> <span class="fl">0.13</span>,  <span class="co">#Observed statistic</span></span>
<span id="cb51-8"><a href="inference-categ-applications.html#cb51-8" tabindex="-1"></a>  <span class="at">direction =</span> <span class="st">&quot;two-sided&quot;</span>  <span class="co">#Direction of the alternative hypothesis</span></span>
<span id="cb51-9"><a href="inference-categ-applications.html#cb51-9" tabindex="-1"></a>)</span></code></pre></div>
<p><img src="16-categorical-applications_files/figure-html/twoPropSimInf-1.png" alt="" width="90%" style="display: block; margin: auto;" /></p>
<p>The <code>two_proportion_test()</code> function generates a null distribution of simulated differences in proportions, with the observed statistic marked with a vertical line and all values as or more extreme than the observed statistic colored red. The figure caption gives the approximate p-value: in this case 181/1000 = 0.181.</p>
<div class="importantbox">
<p>There are a couple of things to note when using the <code>two_proportion_test</code> function:</p>
<ul>
<li>You need to identify which variable is your outcome and which your group using the <code>formula</code> argument.</li>
<li>Specify order of subtraction using <code>first_in_subtraction</code> by putting in EXACTLY the category of the explanatory variable that you want to be first, in quotes — must match capitalization, spaces, etc. for text values!</li>
<li>Specify what is a success using <code>response_value_numerator</code> but putting in EXACTLY the category of the response that you consider a success, in quotes. Again, capitalization, spaces, etc. matter here!</li>
</ul>
</div>
<p>To produce a confidence interval for the true difference in the proportion of patients that survive after receiving CPR, we use <code>two_proportion_bootstrap_CI()</code>, which uses most of the same arguments as the <code>two_proportion_test()</code> function:</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="inference-categ-applications.html#cb52-1" tabindex="-1"></a><span class="fu">two_proportion_bootstrap_CI</span>(</span>
<span id="cb52-2"><a href="inference-categ-applications.html#cb52-2" tabindex="-1"></a>  <span class="at">formula =</span> survival <span class="sc">~</span> group,  <span class="co">#Always do response ~ explanatory</span></span>
<span id="cb52-3"><a href="inference-categ-applications.html#cb52-3" tabindex="-1"></a>  <span class="at">data =</span> cpr,   <span class="co">#Name of the data set</span></span>
<span id="cb52-4"><a href="inference-categ-applications.html#cb52-4" tabindex="-1"></a>  <span class="at">first_in_subtraction =</span> <span class="st">&quot;treatment&quot;</span>, <span class="co">#Value of the explanatory variable that is first in order of subtraction</span></span>
<span id="cb52-5"><a href="inference-categ-applications.html#cb52-5" tabindex="-1"></a>  <span class="at">response_value_numerator =</span> <span class="st">&quot;Survived&quot;</span>,  <span class="co">#Value of response that is a &quot;success&quot;</span></span>
<span id="cb52-6"><a href="inference-categ-applications.html#cb52-6" tabindex="-1"></a>  <span class="at">number_repetitions =</span> <span class="dv">1000</span>, <span class="co">#Number of bootstrap samples</span></span>
<span id="cb52-7"><a href="inference-categ-applications.html#cb52-7" tabindex="-1"></a>  <span class="at">confidence_level =</span> <span class="fl">0.99</span>  <span class="co">#Confidence level, as a proportion</span></span>
<span id="cb52-8"><a href="inference-categ-applications.html#cb52-8" tabindex="-1"></a>)</span></code></pre></div>
<p><img src="16-categorical-applications_files/figure-html/twoPropBootCI-1.png" alt="" width="90%" style="display: block; margin: auto;" /></p>
<p>The main changes for this function are that the <code>as_extreme_as</code> and <code>direction</code> are not needed but a <code>confidence_level</code> choice is required. The provided code produces the distribution of bootstrapped statistics with the bounds of the confidence interval marked, and the value included in the caption. Here, we are 99% confident that the true proportion of patients who survive after receiving CPR is between 0.1 lower and 0.35 higher when patients are given blood thinners compared to when they are not.</p>
</div>
<div id="simulation-based-inference-for-relative-risk" class="section level3 unnumbered hasAnchor">
<h3>Simulation-based inference for relative risk<a href="inference-categ-applications.html#simulation-based-inference-for-relative-risk" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>For inference about the ratio of two proportions, we either use the <code>relative_risk_bootstrap_CI()</code> or the <code>relative_risk_test()</code> functions. These functions assume you have a data frame with the group and outcome included as variables and have similar options as the functions for the difference in two proportions inferences. The data visualization for the relative risk is the same as for the two-sample proportion since it uses the same information (two sample proportions) to calculate the summary measure. The primary modification from <code>two_proportion_test()</code> is to switch from specifying the order of subtraction for the two proportions to defining the group to use in the numerator of the relative risk with the <code>group_numerator</code> option.</p>
<p>Using the CPR and blood thinner study, a call to <code>relative_risk_test()</code> would look like this to have the “treatment” group in the numerator of the relative risk and “survival” as the success for the two proportions being calculated for the two-sided test:</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="inference-categ-applications.html#cb53-1" tabindex="-1"></a><span class="fu">relative_risk_test</span>(</span>
<span id="cb53-2"><a href="inference-categ-applications.html#cb53-2" tabindex="-1"></a>  <span class="at">formula =</span> survival <span class="sc">~</span> group,  <span class="co">#Always do response ~ explanatory</span></span>
<span id="cb53-3"><a href="inference-categ-applications.html#cb53-3" tabindex="-1"></a>  <span class="at">data =</span> cpr,   <span class="co">#Name of the data set</span></span>
<span id="cb53-4"><a href="inference-categ-applications.html#cb53-4" tabindex="-1"></a>  <span class="at">group_numerator =</span> <span class="st">&quot;treatment&quot;</span>, <span class="co">#Value of the explanatory variable that is in the numerator of RR</span></span>
<span id="cb53-5"><a href="inference-categ-applications.html#cb53-5" tabindex="-1"></a>  <span class="at">response_value_numerator =</span> <span class="st">&quot;Survived&quot;</span>,  <span class="co">#Value of response that is a &quot;success&quot;</span></span>
<span id="cb53-6"><a href="inference-categ-applications.html#cb53-6" tabindex="-1"></a>  <span class="at">number_repetitions =</span> <span class="dv">1000</span>,</span>
<span id="cb53-7"><a href="inference-categ-applications.html#cb53-7" tabindex="-1"></a>  <span class="at">as_extreme_as =</span> <span class="fl">1.591</span>,  <span class="co">#Observed statistic</span></span>
<span id="cb53-8"><a href="inference-categ-applications.html#cb53-8" tabindex="-1"></a>  <span class="at">direction =</span> <span class="st">&quot;two-sided&quot;</span>  <span class="co">#Direction of the alternative hypothesis</span></span>
<span id="cb53-9"><a href="inference-categ-applications.html#cb53-9" tabindex="-1"></a>)</span></code></pre></div>
<p><img src="16-categorical-applications_files/figure-html/relriskCI-1.png" alt="" width="90%" style="display: block; margin: auto;" /></p>
<p>The resulting plot provides a caption with estimated relative risk (1.591), the two-sided p-value of 0.0989. Because the relative risk is a ratio, the two-sided p-value can be found by doubling the area in one tail, so only side is shaded in the plot.</p>
<div class="importantbox">
<p>There are a couple of additional things to note when using the <code>relative_risk_test()</code> function:</p>
<ul>
<li>It is possible to encounter relative risks of either 0 or infinity if the proportion in the numerator or denominator is estimated to be 0. The percentage of infinite RRs in the permuted data are reported in the caption (<code>X% Inf</code>) and used in the p-value calculation, but we can not plot infinity. If this is occurring in your data set, we suggest using the <code>adjust = T</code> option to add 0.5 to all the counts to avoid any RRs that are not possible to display. If you are using the adjusted relative risk, you should omit the <code>as_extreme_as</code> option and allow the function to calculate the (adjusted) observed RR for you.</li>
<li>The value of the relative risk under the null hypothesis is displayed at 1 to help with understanding the size of the estimated relative risk.</li>
<li>Two-sided p-values are found by doubling the area in the tail of the distribution where the observed relative risk is found relative to the value of 1 for the relative risk.</li>
<li>If the relative risk is very small (close to 0), the results can be hard to see in the plot – consider changing the group in the numerator to more readily visualize the results.</li>
</ul>
</div>
<p>To produce a confidence interval for the true ratio of the proportion of patients that survive after receiving CPR, we use <code>relative_risk_bootstrap_CI()</code>, which uses most of the same arguments as the <code>relative_risk_test()</code> function:</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="inference-categ-applications.html#cb54-1" tabindex="-1"></a><span class="fu">relative_risk_bootstrap_CI</span>(</span>
<span id="cb54-2"><a href="inference-categ-applications.html#cb54-2" tabindex="-1"></a>  <span class="at">formula =</span> survival <span class="sc">~</span> group,  <span class="co">#Always do response ~ explanatory</span></span>
<span id="cb54-3"><a href="inference-categ-applications.html#cb54-3" tabindex="-1"></a>  <span class="at">data =</span> cpr,   <span class="co">#Name of the data set</span></span>
<span id="cb54-4"><a href="inference-categ-applications.html#cb54-4" tabindex="-1"></a>  <span class="at">group_numerator =</span> <span class="st">&quot;treatment&quot;</span>, <span class="co">#Value of the explanatory variable that is in the numerator of RR</span></span>
<span id="cb54-5"><a href="inference-categ-applications.html#cb54-5" tabindex="-1"></a>  <span class="at">response_value_numerator =</span> <span class="st">&quot;Survived&quot;</span>,  <span class="co">#Value of response that is a &quot;success&quot;</span></span>
<span id="cb54-6"><a href="inference-categ-applications.html#cb54-6" tabindex="-1"></a>  <span class="at">number_repetitions =</span> <span class="dv">1000</span>, <span class="co">#Number of bootstrap samples</span></span>
<span id="cb54-7"><a href="inference-categ-applications.html#cb54-7" tabindex="-1"></a>  <span class="at">confidence_level =</span> <span class="fl">0.99</span>  <span class="co">#Confidence level, as a proportion</span></span>
<span id="cb54-8"><a href="inference-categ-applications.html#cb54-8" tabindex="-1"></a>)</span></code></pre></div>
<p><img src="16-categorical-applications_files/figure-html/relrisktest-1.png" alt="" width="90%" style="display: block; margin: auto;" /></p>
<p>This produces the distribution of bootstrapped statistics with the bounds of the confidence interval marked, and the value included in the caption. Here, we are 99% confident that the true proportion of patients who survive after receiving CPR is between 0.667 and 4.376 <span class="math inline">\(times\)</span> higher when patients are given blood thinners compared to when they are not.</p>
</div>
<div id="theory-based-inference-for-one-proportion" class="section level3 unnumbered hasAnchor">
<h3>Theory-based inference for one proportion<a href="inference-categ-applications.html#theory-based-inference-for-one-proportion" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>For theory-based inference, we can use the built-in R function <code>prop.test()</code>.<a href="#fn143" class="footnote-ref" id="fnref143"><sup>143</sup></a> For a one-proportion test, we need to tell it the number of successes, the number of trials (sample size), and the null value. Using the payday loan regulation example, a call would look like this:</p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="inference-categ-applications.html#cb55-1" tabindex="-1"></a><span class="fu">prop.test</span>(<span class="at">x =</span> <span class="dv">422</span>,  <span class="co">#Number of successes</span></span>
<span id="cb55-2"><a href="inference-categ-applications.html#cb55-2" tabindex="-1"></a>          <span class="at">n =</span> <span class="dv">826</span>, <span class="co">#Number of trials</span></span>
<span id="cb55-3"><a href="inference-categ-applications.html#cb55-3" tabindex="-1"></a>          <span class="at">p =</span> .<span class="dv">5</span>, <span class="co">#Null hypothesis value</span></span>
<span id="cb55-4"><a href="inference-categ-applications.html#cb55-4" tabindex="-1"></a>          <span class="at">alternative =</span> <span class="st">&quot;greater&quot;</span>, <span class="co">#Direction of alternative,</span></span>
<span id="cb55-5"><a href="inference-categ-applications.html#cb55-5" tabindex="-1"></a>          <span class="at">conf.level =</span> <span class="fl">0.95</span>) <span class="co">#Confidence level as a proportion</span></span></code></pre></div>
<pre><code>#&gt; 
#&gt;  1-sample proportions test with continuity correction
#&gt; 
#&gt; data:  422 out of 826
#&gt; X-squared = 0.3, df = 1, p-value = 0.3
#&gt; alternative hypothesis: true p is greater than 0.5
#&gt; 95 percent confidence interval:
#&gt;  0.482 1.000
#&gt; sample estimates:
#&gt;     p 
#&gt; 0.511</code></pre>
<p>In this output, we can get our observed statistic <span class="math inline">\(\hat{p} = 0.51\)</span> in the last line of the output (under <code>sample estimates: p</code>), and the p-value of 0.2656 from the second line of the output. You should always check that the null value and the alternative hypothesis in the output matches the problem.</p>
<div class="importantbox">
<p>You might have noticed that the test statistic reported in the output is <code>X-squared</code> rather than our Z-statistic. This test statistic is equal to our Z-statistic squared, and the p-value is found from what is called a <span class="math inline">\(\chi^2\)</span> distribution (pronounced “kai squared”). To get the Z-statistic from the <code>X-squared</code> statistic, take the positive square root if <span class="math inline">\(\hat{p} &gt; \pi_0\)</span>, and the negative square root if <span class="math inline">\(\hat{p} &lt; \pi_0\)</span>.</p>
</div>
<div class="guidedpractice">
<p>Use the R output to find the value of the Z-statistic.<a href="#fn144" class="footnote-ref" id="fnref144"><sup>144</sup></a></p>
</div>
<p>The <code>prop.test()</code> function will also produce the theory-based confidence interval, but to get the correct confidence interval, <strong>we need to run the function with a two-sided alternative</strong>:<a href="#fn145" class="footnote-ref" id="fnref145"><sup>145</sup></a></p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="inference-categ-applications.html#cb57-1" tabindex="-1"></a><span class="fu">prop.test</span>(<span class="at">x =</span> <span class="dv">422</span>,  <span class="co">#Number of successes</span></span>
<span id="cb57-2"><a href="inference-categ-applications.html#cb57-2" tabindex="-1"></a>          <span class="at">n =</span> <span class="dv">826</span>, <span class="co">#Number of trials</span></span>
<span id="cb57-3"><a href="inference-categ-applications.html#cb57-3" tabindex="-1"></a>          <span class="at">p =</span> .<span class="dv">5</span>, <span class="co">#Null hypothesis value</span></span>
<span id="cb57-4"><a href="inference-categ-applications.html#cb57-4" tabindex="-1"></a>          <span class="at">alternative =</span> <span class="st">&quot;two.sided&quot;</span>, <span class="co">#Direction of alternative,</span></span>
<span id="cb57-5"><a href="inference-categ-applications.html#cb57-5" tabindex="-1"></a>          <span class="at">conf.level =</span> <span class="fl">0.95</span>, <span class="co">#Confidence level as a proportion</span></span>
<span id="cb57-6"><a href="inference-categ-applications.html#cb57-6" tabindex="-1"></a>          <span class="at">correct =</span> <span class="cn">FALSE</span>) <span class="co">#We will not use  a continuity correction</span></span></code></pre></div>
<pre><code>#&gt; 
#&gt;  1-sample proportions test without continuity correction
#&gt; 
#&gt; data:  422 out of 826
#&gt; X-squared = 0.4, df = 1, p-value = 0.5
#&gt; alternative hypothesis: true p is not equal to 0.5
#&gt; 95 percent confidence interval:
#&gt;  0.477 0.545
#&gt; sample estimates:
#&gt;     p 
#&gt; 0.511</code></pre>
<p>From this output, we obtain a 95% confidence interval for the true proportion of payday loan borrowers who support the new regulation of (0.477, 0.545).</p>
</div>
<div id="theory-based-inference-for-a-difference-in-two-proportions" class="section level3 unnumbered hasAnchor">
<h3>Theory-based inference for a difference in two proportions<a href="inference-categ-applications.html#theory-based-inference-for-a-difference-in-two-proportions" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>When comparing two proportions, we use the same function, <code>prop.test</code>, but the inputs are now “vectors” rather than “scalars”. As an example, we will again use the CPR and blood thinner study from Section <a href="foundations-errors.html#two-sided-tests">12.3</a>.</p>
<p>First, use the <code>table()</code> function to determine the number of successes and the sample size in each category of the explanatory variable:</p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="inference-categ-applications.html#cb59-1" tabindex="-1"></a><span class="fu">table</span>(cpr<span class="sc">$</span>survival, cpr<span class="sc">$</span>group)</span></code></pre></div>
<pre><code>#&gt;           
#&gt;            control treatment
#&gt;   Died          39        26
#&gt;   Survived      11        14</code></pre>
<p>From these results (and the example in Section <a href="foundations-errors.html#two-sided-tests">12.3</a>), we see that the Treatment group (call this group 1) had 14 survive (successes) out of 40 patients (sample size); the Control group (call this group 2) had 11 survive out of 50 patients. These counts are input into the <code>prop.test</code> function as follows:</p>
<ul>
<li><code>x</code> = vector of number of successes = <code>c(num successes in group 1, num successes in group 2)</code></li>
<li><code>n</code> = vector of sample sizes = <code>c(sample size for group 1, sample size for group 2)</code></li>
</ul>
<p>R creates a vector using the <code>c()</code> (or “combine”) function. R will take the order of subtraction to be group 1 <span class="math inline">\(-\)</span> group 2.</p>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="inference-categ-applications.html#cb61-1" tabindex="-1"></a><span class="fu">prop.test</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="dv">14</span>, <span class="dv">11</span>), <span class="co">#Number successes in group 1 and group 2</span></span>
<span id="cb61-2"><a href="inference-categ-applications.html#cb61-2" tabindex="-1"></a>          <span class="at">n =</span> <span class="fu">c</span>(<span class="dv">40</span>, <span class="dv">50</span>), <span class="co">#Sample size of group 1 and group 2</span></span>
<span id="cb61-3"><a href="inference-categ-applications.html#cb61-3" tabindex="-1"></a>          <span class="at">alternative =</span> <span class="st">&quot;two.sided&quot;</span>, <span class="co">#Match sign of alternative</span></span>
<span id="cb61-4"><a href="inference-categ-applications.html#cb61-4" tabindex="-1"></a>                                     <span class="co">#for order of subtraction </span></span>
<span id="cb61-5"><a href="inference-categ-applications.html#cb61-5" tabindex="-1"></a>                                     <span class="co">#group 1 - group 2</span></span>
<span id="cb61-6"><a href="inference-categ-applications.html#cb61-6" tabindex="-1"></a>          <span class="at">conf.level =</span> <span class="fl">0.99</span>, <span class="co">#Confidence level as a proportion</span></span>
<span id="cb61-7"><a href="inference-categ-applications.html#cb61-7" tabindex="-1"></a>          <span class="at">correct =</span> <span class="cn">FALSE</span>)  <span class="co">#No continuity correction</span></span></code></pre></div>
<pre><code>#&gt; 
#&gt;  2-sample test for equality of proportions without continuity correction
#&gt; 
#&gt; data:  c out of c14 out of 4011 out of 50
#&gt; X-squared = 2, df = 1, p-value = 0.2
#&gt; alternative hypothesis: two.sided
#&gt; 99 percent confidence interval:
#&gt;  -0.116  0.376
#&gt; sample estimates:
#&gt; prop 1 prop 2 
#&gt;   0.35   0.22</code></pre>
<p>The observed proportions in each group are given under <code>sample estimates: prop 1 prop 2</code>. R will always take (prop 1 - prop 2) as the order of subtraction. If the observed proportions don’t match your calculations of the proportion of successes or are in the wrong order of subtraction, go back and check your inputs to the <code>x</code> and <code>n</code> arguments.</p>
<p>Here, we obtain a p-value of 0.1712 — little to no evidence against the null hypothesis of no difference between the two groups.</p>
<p>Since we used a two-sided alternative in <code>prop.test</code>c, this call also produces the correct confidence interval. Our 99% confidence interval for the true difference in the proportion of patients who survive is <span class="math inline">\((-0.116, 0.376)\)</span>. We are 99% confident that the true proportion of patients who survive under the treatment is between 0.116 lower and 0.376 higher than the true proportion of patients who survive under the control condition. The fact that this confidence interval contains zero also shows us that we have little to no evidence of a difference in probability of survival between the two groups.</p>
<p>The function <code>prop.test</code> will also take a table created by the <code>table</code> function. First, we need to create our table of counts from the raw data, which then becomes our primary input to <code>prop.test()</code>. There is one important step to take before creating our table: R will always put the categories of a categorical variable in alphabetical order when building tables, unless told otherwise.</p>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="inference-categ-applications.html#cb63-1" tabindex="-1"></a>data_tbl <span class="ot">&lt;-</span> <span class="fu">table</span>(cpr<span class="sc">$</span>survival, cpr<span class="sc">$</span>group)</span>
<span id="cb63-2"><a href="inference-categ-applications.html#cb63-2" tabindex="-1"></a>data_tbl</span></code></pre></div>
<pre><code>#&gt;           
#&gt;            control treatment
#&gt;   Died          39        26
#&gt;   Survived      11        14</code></pre>
<p>However, <code>prop.test()</code> will assume that the top row is a “success” and the order of subtraction is (column 1 - column 2). Without re-arranging our table, we would get the wrong order of subtraction and/or the wrong proportion of successes in each group. To fix this, we need to <code>relevel()</code> our inputs to tell R to put them in the order we want:</p>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="inference-categ-applications.html#cb65-1" tabindex="-1"></a><span class="co">#Switch order of subtraction:</span></span>
<span id="cb65-2"><a href="inference-categ-applications.html#cb65-2" tabindex="-1"></a>cpr<span class="sc">$</span>group <span class="ot">&lt;-</span> <span class="fu">relevel</span>(cpr<span class="sc">$</span>group, <span class="at">ref =</span> <span class="st">&quot;treatment&quot;</span>)</span>
<span id="cb65-3"><a href="inference-categ-applications.html#cb65-3" tabindex="-1"></a><span class="fu">table</span>(cpr<span class="sc">$</span>survival, cpr<span class="sc">$</span>group)</span></code></pre></div>
<pre><code>#&gt;           
#&gt;            treatment control
#&gt;   Died            26      39
#&gt;   Survived        14      11</code></pre>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="inference-categ-applications.html#cb67-1" tabindex="-1"></a><span class="co">#Switch &quot;success&quot;:</span></span>
<span id="cb67-2"><a href="inference-categ-applications.html#cb67-2" tabindex="-1"></a>cpr<span class="sc">$</span>survival <span class="ot">&lt;-</span> <span class="fu">relevel</span>(cpr<span class="sc">$</span>survival, <span class="at">ref =</span> <span class="st">&quot;Survived&quot;</span>)</span>
<span id="cb67-3"><a href="inference-categ-applications.html#cb67-3" tabindex="-1"></a><span class="fu">table</span>(cpr<span class="sc">$</span>survival, cpr<span class="sc">$</span>group)</span></code></pre></div>
<pre><code>#&gt;           
#&gt;            treatment control
#&gt;   Survived        14      11
#&gt;   Died            26      39</code></pre>
<p>After re-arranging our table, we can use this <code>data_tbl</code> as the first argument in the <code>prop.test()</code> function:</p>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="inference-categ-applications.html#cb69-1" tabindex="-1"></a>data_tbl <span class="ot">&lt;-</span> <span class="fu">table</span>(cpr<span class="sc">$</span>survival, cpr<span class="sc">$</span>group)</span>
<span id="cb69-2"><a href="inference-categ-applications.html#cb69-2" tabindex="-1"></a></span>
<span id="cb69-3"><a href="inference-categ-applications.html#cb69-3" tabindex="-1"></a>stats<span class="sc">::</span><span class="fu">prop.test</span>(<span class="at">x =</span> data_tbl,</span>
<span id="cb69-4"><a href="inference-categ-applications.html#cb69-4" tabindex="-1"></a>          <span class="at">alternative =</span> <span class="st">&quot;two.sided&quot;</span>,</span>
<span id="cb69-5"><a href="inference-categ-applications.html#cb69-5" tabindex="-1"></a>          <span class="at">conf.level =</span> <span class="fl">0.99</span>, <span class="co">#Confidence level as a proportion</span></span>
<span id="cb69-6"><a href="inference-categ-applications.html#cb69-6" tabindex="-1"></a>          <span class="at">correct =</span> <span class="cn">FALSE</span>)  <span class="co">#No continuity correction</span></span></code></pre></div>
<pre><code>#&gt; 
#&gt;  2-sample test for equality of proportions without continuity correction
#&gt; 
#&gt; data:  data_tbl
#&gt; X-squared = 2, df = 1, p-value = 0.2
#&gt; alternative hypothesis: two.sided
#&gt; 99 percent confidence interval:
#&gt;  -0.14  0.46
#&gt; sample estimates:
#&gt; prop 1 prop 2 
#&gt;   0.56   0.40</code></pre>
</div>
</div>
<div id="catstats-function-summary" class="section level2 hasAnchor" number="16.1">
<h2><span class="header-section-number">16.1</span> <code>catstats</code> function summary<a href="inference-categ-applications.html#catstats-function-summary" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In the previous section, you were introduced to four new R functions in the <code>catstats</code> library. Here we provide a summary of these functions. You can also access the help files for these functions using the <code>?</code> command. For example, type <code>?one_proportion_test</code> into your R console to bring up the help file for the <code>one_proportion_test</code> function. <br></p>
<ol style="list-style-type: decimal">
<li><p><code>one_proportion_test</code>: Simulation-based hypothesis test for a single proportion.</p>
<ul>
<li><code>probability_success</code> = null value</li>
<li><code>sample_size</code> = sample size (<span class="math inline">\(n\)</span>)</li>
<li><code>summary_measure</code> = one of <code>"number"</code> or <code>"proportion"</code> (quotations are important here!) to simulate either sample counts or sample proportions (needs to match the form of the observed statistic)<br />
</li>
<li><code>direction</code> = one of <code>"greater"</code>, <code>"less"</code>, or <code>"two-sided"</code> (quotations are important here!) to match the sign in <span class="math inline">\(H_A\)</span></li>
<li><code>as_extreme_as</code> = value of observed statistic</li>
<li><code>number_repetitions</code> = number of simulated samples to generate (should be at least 1000!) <br></li>
</ul></li>
<li><p><code>one_proportion_bootstrap_CI</code>: Bootstrap confidence interval for one proportion.</p>
<ul>
<li><code>sample_size</code> = sample size (<span class="math inline">\(n\)</span>)</li>
<li><code>number_successes</code> = number of successes (note that <span class="math inline">\(\hat{p}\)</span> = <code>number_successes</code>/<code>sample_size</code>)</li>
<li><code>confidence_level</code> = confidence level as a decimal (e.g., 0.90, 0.95, etc)</li>
<li><code>number_repetitions</code> = number of simulated samples to generate (should be at least 1000!) <br></li>
</ul></li>
<li><p><code>two_proportion_test</code>: Simulation-based hypothesis test for difference in proportions.</p>
<ul>
<li><code>formula</code> = <code>y ~ x</code> where <code>y</code> is the name of the response variable in the data set and <code>x</code> is the name of the explanatory variable</li>
<li><code>data</code> = name of data set</li>
<li><code>first_in_subtraction</code> = category of the explanatory variable which should be first in subtraction, written in quotations</li>
<li><code>response_value_numerator</code> = category of the response variable which we are counting as a “success”, written in quotations</li>
<li><code>direction</code> = one of <code>"greater"</code>, <code>"less"</code>, or <code>"two-sided"</code> (quotations are important here!) to match the sign in <span class="math inline">\(H_A\)</span></li>
<li><code>as_extreme_as</code> = value of observed difference in proportions</li>
<li><code>number_repetitions</code> = number of simulated samples to generate (should be at least 1000!) <br></li>
</ul></li>
<li><p><code>two_proportion_bootstrap_CI</code>: Bootstrap confidence interval for difference in proportions.</p>
<ul>
<li><code>formula</code> = <code>y ~ x</code> where <code>y</code> is the name of the response variable in the data set and <code>x</code> is the name of the explanatory variable</li>
<li><code>data</code> = name of data set</li>
<li><code>first_in_subtraction</code> = category of the explanatory variable which should be first in subtraction, written in quotations</li>
<li><code>response_value_numerator</code> = category of the response variable which we are counting as a “success”, written in quotations</li>
<li><code>confidence_level</code> = confidence level as a decimal (e.g., 0.90, 0.95, etc)</li>
<li><code>number_repetitions</code> = number of simulated samples to generate (should be at least 1000!)</li>
</ul></li>
<li><p><code>relative_risk_test</code>: Simulation-based hypothesis test for relative risk.</p>
<ul>
<li><code>formula</code> = <code>y ~ x</code> where <code>y</code> is the name of the response variable in the data set and <code>x</code> is the name of the explanatory variable</li>
<li><code>data</code> = name of data set</li>
<li><code>group_numerator</code> = category of the explanatory variable which should in numerator , written in quotations</li>
<li><code>response_value_numerator</code> = category of the response variable which we are counting as a “success”, written in quotations</li>
<li><code>direction</code> = one of <code>"greater"</code>, <code>"less"</code>, or <code>"two-sided"</code> (quotations are important here!) to match the sign in <span class="math inline">\(H_A\)</span></li>
<li><code>as_extreme_as</code> = value of observed relative risk</li>
<li><code>adjust</code> = one of <code>T</code> or <code>F</code>, use <code>T</code> if infinite relative risks are encountered</li>
<li><code>number_repetitions</code> = number of simulated samples to generate (should be at least 1000!) <br></li>
</ul></li>
<li><p><code>relative_risk_bootstrap_CI</code>: Bootstrap confidence interval for relative risk.</p>
<ul>
<li><code>formula</code> = <code>y ~ x</code> where <code>y</code> is the name of the response variable in the data set and <code>x</code> is the name of the explanatory variable</li>
<li><code>data</code> = name of data set</li>
<li><code>group_numerator</code> = category of the explanatory variable which should in numerator , written in quotations</li>
<li><code>response_value_numerator</code> = category of the response variable which we are counting as a “success”, written in quotations</li>
<li><code>adjust</code> = one of <code>T</code> or <code>F</code>, use <code>T</code> if infinite relative risks are encountered</li>
<li><code>confidence_level</code> = confidence level as a decimal (e.g., 0.90, 0.95, etc)</li>
<li><code>number_repetitions</code> = number of simulated samples to generate (should be at least 1000!)</li>
</ul></li>
</ol>
<!-- to make pretty someday.... -->
<!-- ```{r catstats-sum-prop} -->
<!-- catstats_prop_table <- tribble( -->
<!--   ~name,    ~description, ~arguments, -->
<!-- "one_proportion_test",  "Simulation-based hypothesis test for a single proportion", "probability_success = null value", -->
<!-- "",  "", "sample_size = sample size ($n$)", -->
<!-- "",  "", "number_repetitions = number of simulated samples to generate", -->
<!-- "",  "", "as_extreme_as = observed statistic", -->
<!-- "",  "", "direction = one of: `greater`, `less`, or `two-sided` to match sign in $H_A$", -->
<!-- "",  "", "number_repetitions = number of simulated samples to generate", -->
<!-- ) -->
<!-- catstats_prop_table %>% -->
<!--  kable(caption = "Summary of `catstats` functions for simulation-based inference for proportions.",  -->
<!--     col.names = c("Function Name", "Description", "Inputs")) %>% -->
<!--  kable_styling() -->
<!-- ``` -->

</div>
</div>



<!-- ::: {.underconstruction} -->
<!-- Divide up the content in this chapter and move across Chapters 17-19 -->
<!-- ::: -->
<!-- ::: {.underconstruction} -->
<!-- Old content - revise as needed -->
<!-- ::: -->
</div>
<div class="footnotes">
<hr />
<ol start="143">
<li id="fn143"><p>By “built-in”, we mean that it is in the R “base” library, so no packages need to be loaded.<a href="inference-categ-applications.html#fnref143" class="footnote-back">↩︎</a></p></li>
<li id="fn144"><p>Since our sample proportion <span class="math inline">\(\hat{p} = 0.511\)</span> is larger than the null value <span class="math inline">\(\pi_0 = 0.5\)</span>, we know our Z-statistic will be positive. Thus, <span class="math inline">\(Z = +\sqrt{0.34988} = 0.592\)</span>. Check these values using the formula for the Z-statistic presented in Section <a href="inference-one-prop.html#theory-prop">14.3</a>.<a href="inference-categ-applications.html#fnref144" class="footnote-back">↩︎</a></p></li>
<li id="fn145"><p>If you run <code>prop.test</code> with a one-sided alternative (<code>"greater"</code> or <code>"less"</code>), then R will report what is called a “one-sided confidence interval”, where one of the endpoints is either 0 (for a “less” alternative) or 1 (for a “greater” alternative). This is equivalent to only producing an upper bound or a lower bound, respectively, for the parameter of interest.<a href="inference-categ-applications.html#fnref145" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="inference-two-props.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="inference-one-mean.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": false,
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/MTstateIntroStats/IntroStatTextbook/edit/master/16-categorical-applications.Rmd",
    "text": "Edit"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["stat216-textbook.pdf"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
